code-for-canada/project-thundercat

README.md
Right now JS changes don't hot re-load, so you have to log into the front end container and run `yarn build` to see your changes. This PR adds documentation for this.
We're working on making hot re-loading work locally by following this tutorial: https://blog.bam.tech/developper-news/dockerize-your-app-and-keep-hot-reloading
The goal is, instead of this locally:
We want this:
=> Documentation update: How to view your JS changes

frontend/entrypoint.sh
In a previous PR, I broke master by replacing `yarn build` with `yarn start` so make sure the front end container stays up. For now, we also need `yarn build` because nginx points to the built version.
=> Bug fix: entrypoint.sh change broke master

nginx/Dockerfile
Locking nginx version to 1.15.8. Technically we were already using this, but now it is locked so that if a new version is released we can make sure that it works rather than suddenly having a new version one day.
=> Nginx Version: nginx 1.15.8

frontend/public/index.html, frontend/public/manifest.json, frontend/src/App.css, frontend/src/App.js, frontend/src/Experiment.jsx, frontend/src/Home.jsx, frontend/src/Home.test.js, frontend/src/Status.jsx
This PR does some look and feel prep for the project panel.
- uses `Prototype` over `Experiment` to be consistent with how we talk about building
- removes API call from the home page because it's not needed now that we have a status page
- makes all the backgrounds white to match /status
- spelling of competency (screenshot outdated)
=> Look and feel - consistency

frontend/package.json, frontend/yarn.lock
Security Patch to solve vulnerabilities detected by Snyk:
* Mem@1.1.0 -> ^4.1.0 (solves DoS vulnerability)
* Braces@1.8.5 -> ^2.3.2 (solved ReDoS vulnerability)
Mem and Braces are sub-dependencies of react-scripts. React-scripts@2.1.3 requires that Mem's version is >= 1.1.0 and Braces version is >= 1.8.5. However, these two packages have known vulnerabilities at these versions (as mentioned above). This patch forces these packages to have more recent versions (or higher) to remove these vulnerabilities.
=> Security Patch 

frontend/package.json, frontend/yarn.lock
Reverts code-for-canada/project-thundercat#46
This change did not actually fix the sub dependency vulnerability so reverting because this code is no longer needed.
=> Revert "Security Patch "

.gitignore, SETUP.md, docs/snyk.md, run-snyk-tests.sh
Script now runs snyk inside the container (as it does online for PRs) and outputs to two git-ignored hmtl files for ease of viewing.
* Added steps in SETUP.md
* How to install snyk-to-html
* **Script will not run without this step, please run the command locally**
* Updated run-skyn-test script
* Run snyk within containers
* Output results to
* snyk_results_backend.html
* snyk_results_frontend.html
* Updated gitignore (to ignore the files)
=> SNYK Script update

frontend/src/components/eMIB/Emib.jsx
Adding a fix to remove the following warning.
Fixed bug by replacing `<a>` with `<div>` and coloring `<div>` to look like an `<a>` (This will eventually be replaced with a button anyway)
The warning (as reported by @fnormand01 ):
=> Fix to remove warning from Emib.jsx file

frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/Tab.jsx, frontend/src/components/eMIB/TestTabs.jsx, frontend/src/test/Emib.test.js, frontend/src/test/Tabs.test.js, frontend/src/test/TestTabs.test.js
Restructure of Emib and tests to include a component with 3 tabs for the test (instructions, background, and inbox) rather than managing 3 individual components within the Emib component.
Addition and update of relevant tests.
Also added "Tab" component, which can hopefully be reused elsewhere
Background Tab:
Instructions Tab:
Inbox Tab:
=> Emib tab restructure

frontend/src/tests/components/status/StatusCheck.test.js, frontend/src/tests/components/status/SystemCheck.test.js
Small patch to fix StatusCheck and SystemCheck tests (addition of space in constants within the test)
Run tests to verify that they all pass
=> Adding space to fix bug with StatusCheck and SystemCheck tests

frontend/src/Experiment.jsx, frontend/src/components/eMIB/Confirmation.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/tests/components/eMIB/Emib.test.js
Changed look and feel of "Start Test", "Next", and "Exit Test" buttons to use Aurora.
Updated relevant tests.
Please provide if applicable.
Manual steps to test this functionality:
- Start up the application
- Navigate through the tests, start to finish, using only `Tab` and `Enter` keys
NOTE: Merged Master into branch to get the fix from PR #69
=> Next Button Navigation patch

frontend/src/components/eMIB/Evaluation.jsx, frontend/src/components/eMIB/Overview.jsx, frontend/src/components/eMIB/TipsOnTest.jsx, frontend/src/text_resources.js
Added the content of Evaluation in its respective component and format everything. 
I also updated the links in Overview and Tips on Taking the eMIB, since these links refer to **Key Leadership Competencies** section in Evaluation component. All the warnings are now gone.
Important Section Added [ENGLISH]:
Important Section Added [FRENCH]:
1. Go to Prototype tab.
2. Click _Start eMIB Sample Test_.
3. Click _Next_.
4. Make sure that Evaluation section looks good and is the same as the wireframes (except the content itself).
=> [How To Page] Building the Evaluation Section

frontend/src/App.js, frontend/src/Home.jsx, frontend/src/Prototype.jsx, frontend/src/Status.jsx, frontend/src/components/commons/ContentContainer.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/css/App.css, frontend/src/tests/Home.test.js, frontend/src/text_resources.js
Went through the application with Joey this morning. We decided to add the banner to a few more places to make things look consistent (basically everywhere except within the actual eMIB).
I also talked to Michael this morning about how it might be good to have a consistent way to center and left align content. We decided to follow what canada.ca does with `max-width: 1140px` and auto margins. 
I did all this by making a component called `ContentContainer` that conditionally shows the banner and centers all it's content.
1.  Go to all pages.
2.  Notice the banners and content centering.
Any concerns that need to be addressed in …
=> Center content and fix banners

frontend/src/App.js, frontend/src/components/commons/BackToTop.jsx, frontend/src/components/commons/ContentContainer.jsx, frontend/src/components/commons/ProgressPane.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/Evaluation.jsx, frontend/src/components/eMIB/Overview.jsx, frontend/src/components/eMIB/TestInstructions.jsx, frontend/src/components/eMIB/TipsOnTest.jsx, frontend/src/css/App.css, frontend/src/tests/components/eMIB/Emib.test.js
From now on, CSS that is specific to a component should live in that components file. 
App.css should be used for overrides of existing CSS class names, tags, or in very specific cases where we'd want to add a new class. For example, a h1 with a green line after it: `h1.green-divider:after`
If you want an easier way to review this, each commit addresses a specific item of CSS and has a description that should make it easier to read. 
No visual changes.
Manual steps to reproduce this functionality: Clean through entire app, you should see no changes.
=> CSS Cleanup

frontend/src/components/commons/BackToTop.jsx
Fixing a JS error on Sample Test. We had a memory leak because we weren't removing an event listener that we added.
1.  Go to sample test page and enter test with console open.
2.  You should see no console errors.
=> Bug fix: remove event listener js error

frontend/src/components/eMIB/HowTo.jsx, frontend/src/tests/components/eMIB/HowTo.test.js
Fixed the progress bar language toggle bug. Now the translation is also applied to the progress bar.
**Page in English:**
**Page in French:**
1.  Go to Prototype tab.
2.  Click _Start eMIB Sample Test_.
3.  Make sure that the progress bar is also translated when you hit 'English/French' button
=> [Pre-Test Information] Progress Bar Language Toggle Bug Fixed

frontend/src/components/commons/SideNavigation.jsx, frontend/src/components/eMIB/TestInstructions.jsx, frontend/src/css/App.css
Correcting formatting issues with Instructions within the TestTabs, so that they more accurately confirm to the correct look and feel in the wireframes.
1. Go to Start Test
2. Verify that my changes do not cause any issues in the pre-instructions formatting
3. Continue to the test
4. Verify that the Instruction pages display correctly
NOTE:
There is a bug/glitch where the buttons in the SideNav (in test instructions page) resize seemingly randomly. I will make a seperate PR to address this.
=> [Test Instructions] Formatting Instructions and TestTabs

frontend/src/components/commons/SideNavigation.jsx, frontend/src/components/commons/TabNavigation.jsx
Added scrolling to content of SideNav, allowing TestTabs and SideNav buttons to remain stationary; Also added height to body of TestTabs, so that the bottom of the tab does not resize when changing tabs.
1.  Start eMiB
2. Go to the test
3. Verify that tas render correctly and that scrolling does not move the tabs or side nav
NOTE:
Does not render correctly in IE. This is caused by a different bug that will be resolved in a separate PR.
=> Create a max height to the emib tabs

frontend/src/App.js, frontend/src/text_resources.js
Added _aria-label_, _aria-current_ and _roles_ inside < nav > tags in order to meet the menus accessibility requirements.
(Not useful for this PR)
1.  Enable the narrator on your machine.
2.  Open CAT in your browser.
3.  Hit _tab_ until the **Home** page tab is focused.
4.  Listen the narrator and make sure he says "_main menu_" and the current selected tab (Home, Prototype or Status) + make sure that the narrator says "_language toggle button_" when the concerned button is selected.
=> [Accessibility Review] Menus

frontend/src/text_resources.js
Very simple PR: I just removed the extra space in the French description of Tips on Taking the eMIB component.
1.  Go to Prototype tab.
2.  Click _Start eMIB Sample Test_.
3.  Make sure that the French version of Tips on Taking the eMIB component looks good.
=> [Bug Fix] Removed Extra Space in French Desc of Tips on Taking the eMIB

frontend/src/css/cat-theme.css
Put a white background to **Back to top** button, so even if it overlaps the text when the page is shrunk, the button looks good.
1.  Go to _Prototype_ tab.
2.  Click _Start the eMIB Sample Test_.
3.  Shrink your browser page.
4.  Scroll down and once the _Back to top_ button appears, make sure it looks good even if it overlaps the text.
=> [Bug Fix] Back to top button was overlapping the text when the page is shrunk

frontend/package.json, frontend/yarn.lock
Restoring Dev dependencies; upping version of eslint to match needs of react-js 2.1.5; undo of part of #107 
- eslint 5.6.0 -> 5.12.0 (to match react-js 2.1.5)
1.  Delete frontend/node_modules
2. build and ensure there are no errors/warnings.
=> [Dependency fix] Restoring dev dependencies

backend/entrypoint.sh
By default, we want to run our database migrations on build. This means the server will get these migrations, and whenever we pull new code locally it will run migrations. 
Right now the dev server is failing the DB check because it never ran migrations. 
Current error on dev:
If you are in development mode, and don't want them to run automatically, you will have to comment out this file.
1.  docker-compose build should execute without errors and run migrations
=> Docker - run database migrations on build

frontend/package.json, frontend/src/Status.jsx, frontend/src/components/commons/Notepad.jsx, frontend/src/components/commons/TabNavigation.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/css/cat-theme.css, frontend/src/css/emib-tabs.css, frontend/src/text_resources.js, frontend/yarn.lock
I added a notepad next to the test side navigation tabs. I tried to replicate the design as much as possible.
To do that, I used a React library called _'react-textarea-autosize'_ to get the height of the notepad text zone dynamic.
For now, there is a max of 3000 characters allowed. May be updated in the future.
No unit test has been added, since we are not storing any of the notes for now. Unit tests for that new component will be added once notes storing using Redux will be configured.
Also, when using _tab navigation_, note that **Submit test** button becomes selected before the **notepad window**. However, the test footer will fix that issue.
**English Version:**
**French Version:**
**Overflow Example:** …
=> [Functionality] Building Notepad

frontend/src/App.js, frontend/src/components/commons/SideNavigation.jsx, frontend/src/components/commons/Tab.jsx, frontend/src/components/commons/TabNavigation.jsx, frontend/src/tests/components/commons/Tab.test.js, frontend/src/tests/components/commons/TabNavigation.test.js
Added:
- role="menubar" to each <ul> in a <nav>
- role="menuitem" to each <li> in a <nav>
- removed extraneous roles
N/A
1. Navigate into the test in IE (Narrator only works in IE)
2. Turn on the Narrator
3. Ensure that the narrator properly detects the menus, selected an unselected tabs
4. Ensure that there are not cosmetic differences in IE or Chrome
=> [Accessibility] Roles

frontend/src/components/eMIB/Background.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/text_resources.js
For our next demo, we want to make our "empty" features look a little nicer. 
This PR ads coming soon text to the Inbox and Background tabs.
1.  Go to eMIB test and look at Background and Inbox tabs.
=> Add padding and change text

frontend/src/App.js
Adding header tag (with role and aria level) to wrap around the main nav
N/A no visual difference
1.  Look at the Application and make sure there are no visual differences (would only effect the main nav)
=> [Accessibility] Header Tag

frontend/src/components/commons/Notepad.jsx, frontend/src/components/commons/SideNavigation.jsx, frontend/src/components/commons/TabNavigation.jsx, frontend/src/components/commons/TestFooter.jsx
I met Joey (UX Designer) and made some style updates related to the notepad and the test footer components.
1.  Go to _Prototype_ tab.
2.  Click _Star eMIB Sample Test_.
3.  Pass the instructions.
4. Make sure that the notepad and the test footer look good in all browsers.
=> [Pairing Design Session] Notepad and Test Footer Style Updates

frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/css/cat-theme.css, frontend/src/text_resources.js
This PR adds popup boxes for the org chart image descriptions on the background page.
Notes:
- this does not include the french translations
- I used buttons rather than links because links without a valid href generate warnings when compiling.
1.  Navigate through the eMiB pre-test instruction pages to the eMIB itself
2.  In the background page, scroll down to the org charts.
3.  Click the link below the org charts to open the popup box with descriptuion
Applicable for …
=> [Background Page] Image Dailog

frontend/src/components/eMIB/Emib.jsx, frontend/src/text_resources.js
I added the real content in the quit test popup box in both official languages.
**English Version:**
**French Version:**
1.  Start the eMIB sample test.
3.  Click Quit test and make sure that the content is right (in both official languages).
=> [Quit Test Flow] Real Content Insert

frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/text_resources.js
Added real english content to the Image Dialogs in the Background section.
Added longdesc referring to the id of the image description button
1.  Navigate through Prototype -> Pre-test Instructions -> Background
2. Verify that the popups still work/show the correct text
=> [Image Dialog] Addition of EN Content

frontend/src/components/eMIB/Emib.jsx
Simplified the enabled/disabled **Quit Test** button logic in eMIB.jsx component.
(N/A)
3.  Click **Quit Test** and make sure everything still working as expected, meaning that the button becomes enabled only when all the checkboxes are checked.
=> [Quit Test Flow] Simplified the enabled/disabled Quit Test button logic

frontend/package.json, frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/css/cat-theme.css, frontend/src/css/react-medium-image-zoom.css, frontend/yarn.lock
I added a zoom functionality on both images in **Background Information** section. You have to **click** on the image in order to zoom it.
Details to consider for this PR:
- We need zoomed images of better quality, because they are blurred
- IE zoom-in / zoom-out cursor styles are not compatible with IE, so I put the _pointer_ cursor style for IE
**First Image - Zoomed:**
**Second Image - Zoomed:**
2.  Complete the _pre-test information_ section.
3.  Go in _Background_ section and zoom-in / zoom-out both images in all browsers and make sure everything works well, including the navigation with the keyboard.
Screenshot of unit tests …
=> [Zoom Functionality] Added zoom functionality on images in Background section

.travis.yml, docs/PULL_REQUEST_TEMPLATE.md, frontend/src/tests/components/commons/TestFooter.test.js
Added Travis in order to automate the front end/back end tests. To do that, we simply added Travis to this GutHub repository and added a config file called _.travis.yml_.
I also updated the PR Template, since we don't need the test screenshot and all tests passed checkbox.
**When all tests are passing:**
**If some tests are failing (done by pushing commit #https://github.com/code-for-canada/project-thundercat/pull/139/commits/12ea70908c6add1059ab9685af34df27ae91ebff):**
**Failing tests from Travis console:**
- You can only test that by opening a new PR OR add a commit to an existing one.
**Screenshot from Travis console (frontend):**
**Screenshot …
=> [CI Tools] Adding Travis CI Tool

frontend/src/components/eMIB/Overview.jsx, frontend/src/text_resources.js
Adding text to instructions Overview, noting that instructions will still be available in the test
(let me know if this should be in a different part of the Overview page)
1.  Protype -> Start eMIB
2.  Look at the Overview page
3.  This will also change the in-test instructions
=> [Instructions] Adding Instructions Text

frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/components/eMIB/InTestInstructions.jsx
This fixes the translation bug for the side navigation of the in test instructions.
1.  Go to the emib sample test on the instructions tab.
2. Toggle the language and notice the language updates on the side navigation.
=> Refactor / bug fix: instructions side bar localization bug

frontend/src/components/commons/Notepad.jsx, frontend/src/components/commons/TabNavigation.jsx, frontend/src/components/commons/TestFooter.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx
Now, when you are within the test, you can use a screen anywhere between 900-1400. You'll get more room for content if you have a larger screen.
Paired with: @fnormand01 
1.  Go to eMIB test.
2.  Resize the screen.
3.  Repeat in IE.
=> eMIB in test - screens between 900 and 1400px

frontend/src/components/commons/PopupBox.jsx, frontend/src/components/commons/SystemMessage.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/css/cat-theme.css, frontend/src/tests/components/commons/SystemMessage.test.js
I updated the popup box styles to match the design. I met with the UX Designer to do these changes.
**Submit Test Popup Box:**
**Quit Test Popup Box:**
3.  Click on _Submit test_ and _Quit test_ buttons and make sure these popup boxes look good and do what they are suppose to do.
=> [Design Session] Updated popup box styles to match the design

frontend/src/components/commons/Notepad.jsx, frontend/src/components/commons/SideNavigation.jsx, frontend/src/text_resources.js
I added hide/open notepad functionality and updated notepad styles. These style updates have also been approved by the UX Designer. 
Also, the notepad content is saved using a state, so even if you collapse the notepad, the content of it will be kept and restored when you'll reopen the notepad.
**Opened Notepad:**
**Hidden Notepad:**
2.  Complete the pre-instruction process.
3.  Play with the notepad and make sure it looks good and works well in all browsers.
=> [Notepad] Added Hide/Open Notepad Functionality

frontend/src/components/commons/TabNavigation.jsx, frontend/src/components/eMIB/EmibTabs.jsx
I simply added a new prop in _TabNavigation.jsx_ component, so we can now customize it when using it. For now, this component was only used by _EmibTabs.jsx_ component, but in the future, this component will be used in other places, so that is important to be able to customize the style.
**Still look the same as before:**
3.  Make sure that the eMIB interface looks the same as before, especially the tab navigation window.
=> [Tab Navigation] Added new prop for style customization

frontend/src/Home.jsx, frontend/src/components/authentication/AuthenticationTabs.jsx, frontend/src/components/authentication/CreateAccountForm.jsx, frontend/src/components/authentication/LoginForm.jsx, frontend/src/css/create-account-form.css, frontend/src/text_resources.js
I implemented some new authentication components, meaning one for the login and one for the account creation.
**Login:**
There is no validation at all in this component. As soon as you click _Login_, you'll be redirected to the home page with a welcome message. Basic authentication logic has been used to produce this fake login behavior. This will be removed once we'll introduce the back end implementation of the login feature.
Note that as soon as you refresh or change the page, the login process will restart, meaning that you will not stay logged in for now.
**Created Account:**
In this component, there is a lot of validation. All fields are validated using RegEx validation (see PR https://github.com/code-for-canada/project-thundercat/pull/154). Also, the _Create account_ button stay …
=> [Login & Create Account] Added Login Form and Create Account Form and Included Validation

frontend/src/components/eMIB/EmailPreview.jsx
Added formatting to truncate the subject and from lines in the email preview;
Added logic to drop everything after the first "(" in the from line.
1.  Go to Prototype -> Start eMIB
2. Navigate through pre-test instructions
3. Start Test
4. Open the Inbox tab
=> [Inbox] Abbreviate email preview

frontend/src/components/eMIB/CollapsingItemContainer.jsx, frontend/src/css/collapsing-item.css, frontend/src/tests/components/eMIB/CollapsingItemContainer.test.js
I implemented a new generic component called _'CollapsingItemContainer'_ that handle collapsing items to view replies and tasks in the inbox.
**How to use this new component:**
First, you need to import the following:
Then, use it like that:
You can always change the icon (email or task) by using the following variable:
- ICON_TYPE
**Collapsing Item Hidden (task icon)**
(Task content will be done in a future PR, since we don't have the design yet)
**Collapsing Item Hidden (email icon):**
(Task content will be done in a future PR,)
**Expanded View:**
**- Note that this new component is not very testable except if you add it in some component to see what it looks like, as shown in the description (See '_How to use this new …
=> [View Emails/Task] Created new generic collapsing item component to view emails and tasks

frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailPreview.jsx, frontend/src/css/inbox.css
Changing the tag of the 'Email #x" from h6 to h2, but making it look like an h6 to meet look and feel.
No visual difference (which was the point)
1.  Go to Prototype -> Start eMIB -> pre-test instructions -> Start Test
2.  Open the Inbox Tab
3. Look at the email view
=> [Email] Format email header

frontend/src/components/eMIB/ResponseItem.jsx, frontend/src/tests/components/eMIB/ResponseItem.test.js, frontend/src/text_resources.js
I implemented a new component called '_ResponseItem_' that handle the display of the responses. 
**This component needs to be used as part as the body of the _'CollapsingItemContainer'_ component.**
**How to use this new component:**
First, you need to import the following:
Then, use them like that:
You can always change the icon (email or task) and change the response type (reply, reply all, forward) using the following variables:
- ICON_TYPE
- RESPONSE_TYPE
**Collapsing Item Hidden (email icon):**
**Once Expanded (response type = reply):**
**Once Expanded (response type = reply all):**
**Once Expanded (response type = forward):**
**- Note that this new component is not very testable except if you add it in some component to …
=> [Add an Email] Created new component that displays the the response content

frontend/src/components/eMIB/Email.jsx
Emails hit the side of the notepad. This matches the padding on the left.
1.  Go to Inbox page in the sample test.
2.  Notice the padding change.
=> [Inbox] Add padding to the right side of the emails

frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/components/eMIB/Email.test.js, frontend/src/tests/components/eMIB/Inbox.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js, frontend/src/text_resources.js
Add an email or task updates the counts in redux, and displays the counts at the top of each email.
1.  Go to sample test inbox.
2.  Click add task and save.
3. Click add email and save.
4. Notice counts increasing.
=> [Inbox] Add email action counts into redux

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditEmailActionDialog.jsx, frontend/src/components/eMIB/ResponseItem.jsx, frontend/src/css/cat-theme.css, frontend/src/text_resources.js
I created a form that will allow the candidates to add an email response for the specified email. This form is displayed when you click on **'Add email response'** in the inbox.
**Note that the radio buttons are not functional and the **Save response** button has the same behavior than before.**
**Add Email Form - Part 1:**
**Add Email Form - Part 2:**
4.  Click on _Add email response_ and make sure that the form looks good.
=> [Add Email] Created the add email form

frontend/src/components/commons/PopupBox.jsx, frontend/src/components/commons/SystemMessage.jsx
I simply updated _PopupBox_ and _SystemMessage_ styles to fix a little modal display bug.
This bug was triggered when the page was shrunk.
**Before:**
**After:**
3.  Click on _Quit test_.
4. Make sure the modal box looks good, even if you shrink the page.
=> [Bug Fix] Fixed modal display bug

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailPreview.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/components/eMIB/constants.js, frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/components/eMIB/ActionViewEmail.test.js, frontend/src/tests/components/eMIB/EditActionDialog.test.js, frontend/src/tests/components/eMIB/Email.test.js, frontend/src/tests/components/eMIB/EmailPreview.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js, frontend/src/text_resources.js
No user facing changes. This preps us to show a saved email action to the user.
- Followed EmivInboxRedux tech spec for storing data
- Re-named components to be consistent 
- Defined enums and PropType shapes in eMIB/constants.js
- Modified `addEmail` to take in an `actionShape` and added a test
- Saved state of the add email form into state and then redux on save button press
The last part of "Add email" is displaying it in the Email component.
No changes to the UI.
1.  Navigate to eMIB Sample Test Inbox.
2.  Click on "Add email" or "Add task" and notice no breaking changes.
~~- [ ] I …
=> [Inbox] Add email action handles action data

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/components/eMIB/Email.test.js
Displays email based on the actions in redux.
1.  Go to the inbox on the sample test.
2. Try adding an email
=> [Inbox] Display email from redux

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/constants.js
Object.keys is compatible but not Object.values with IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys
1.  Open up the application on IE.
=> Fix IE JS Compatibility Bug

frontend/src/text_resources.js
There are no more drafts, so replacing the content with something that makes more sense.
1.  Go to sample test and click submit.
=> Update content of submit dialog

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/constants.js, frontend/src/tests/components/eMIB/ActionViewEmail.test.js, frontend/src/tests/components/eMIB/ActionViewTask.test.js
I simply replaced all 'reasonForAction' with 'reasonsForAction' (with an s).
**(No Visual Changes)**
- Make sure that the app is still the same as before
=> [Refactoring] Replaced all 'reasonForAction' with 'reasonsForAction'

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx
I simplified the aria-labels and roles structure in _ActionViewEmail.jsx_ and in _ActionViewTask.jsx_ components:
- Removed all dialog roles
- refactored aria-labels
- replaced all the field's titles (was <p> tags) with header tags
**(No Visual Changes)**
4.  Add an _Email response_.
5.  Save you email response.
6.  Turn on the narrator settings.
7. Take a look at the your response by using the collapsing item at the bottom.
8. Use the keyboard to navigate in the response view item.
9.  Make sure that the narrator reads all the information inside this response item.
=> [Add/Edit Email] Simplified aria-labels and roles

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js
Several styling changes from design pairing with Joey, including:
- Removing unnecessary padding and margins
- Increasing width of the modal header
- Adding a close button
- Adding a pointer cursor over the Edit Email Radio buttons
Before:
After:
1.  Enter the test
2.  Open the Inbox Tab
3.  Look at the differences in the dialog when adding/modifying an email/task
=> [EditActionDialog] Design pairing fixes

frontend/src/components/eMIB/ActionViewEmail.jsx
There was some display bugs in the email response view when the **To** and/or **Cc** fields were empty. This bug is now fixed.
**Before:**
**After (empty cc field):**
**After (empty to and cc fields):**
4.  Add email responses with empty '_to_' and/or '_cc_' fields and make sure that the response views still look good.
=> [Add/Edit Email] Fixing Display Bugs

frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/components/eMIB/ActionViewTask.test.js, frontend/src/tests/components/eMIB/EditActionDialog.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js
I implemented the 'Edit Task' functionality the same way @MichaelCherry did in PR https://github.com/code-for-canada/project-thundercat/pull/192.
**Create a Task (1):**
**Create a Task (2):**
**Update Task (1):**
**Update Task (2):**
**Task Updated:**
3.  Open _Inbox_ tab.
4.  Create a new Task.
5.  Edit this new Task and make sure everything is working fine and looking good.
=> [Edit Task] Added Edit Task Functionality

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js
This PR fixes two minor bugs related to the _'read email'_ state:
- Mark emails _'as read'_ as soon as we click on them
- Mark emails _'as read'_ when we add action(s), meaning adding an email response and/or a task
**Bug 1**
---
**Initial states when you open the Inbox (all emails are marked as unread):*
**As soon as I select another email (first email and the selected one are marked as read):**
**Bug 2**
---
**Initial states when you open the Inbox (all emails are marked as unread):*
**Adding an action (email response or task):**
**Result (the first email is now marked as read):**
4.  In the …
=> [Bug Fixes] Fixing 'read email' Bugs

frontend/src/components/eMIB/Email.jsx, frontend/src/tests/components/eMIB/Email.test.js
Added code to:
- Create array by splitting email body on \n characters
- Iterate over array, wrapping each element in <p> tags
NOTE: this looks the same if the body contains '\n', '\n\n', '\n\n\n', etc.
Before:
After:
1.  Go to Prototype -> Start eMIB -> Pre-test instructions -> Start Test
2.  Open the Inbox tab
3.  See that all the emails are nicely formatted
=> [Email] Formatting email body

frontend/src/components/eMIB/Inbox.jsx
After discussion, I simply removed the _'mark email as read'_ as soon as we select an email functionality. The emails become _'as read'_ only if you select another email or if you add action(s) on them.
(N/A)
4.  Select an email other than the first one and make sure that it still unread.
5.  Add an action (email response or task) and make sure that it becomes _'read'_.
=> [Bug Fixes] Removed 'mark as read' as soon as we select an email functionality

.travis.yml, frontend/src/tests/components/eMIB/EditActionDialog.test.js
I updated Travis settings, so it should now fail if there are any warnings **or** errors during the build.
**All tests still passed:**
Backend:
Frontend:
- The only way to test that is to run tests using Travis in a new PR or one of the existing ones.
=> [Travis] Updating Travis settings to treat warnings as errors

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js
"Submit response" is now disabled immediately after clicking it so that users cannot accidentally duplicate emails if double clicking.
1.  Go to Prototype -> Start eMIB -> Pre-test Instructions -> Start Test"
2.  Add an email or task
3.  Fill out the form
4.  Click "Submit response" rapidly multiple times
5.  See that only one response was submitted
6.  Repeat for editing
=> [Bug Fix] Duplicate email bug

frontend/package.json, frontend/src/tests/components/eMIB/ActionViewEmail.test.js, frontend/yarn.lock
This patch resolved the following vulnerabilities:
- [js-yaml](https://app.snyk.io/test/npm/js-yaml) (2)
- [handlebars](https://app.snyk.io/test/npm/handlebars)
Upgrades:
- "mem": ">=4.1.0" to "mem": ">=4.3.0" (https://snyk.io/vuln/npm:mem:20180117)
- "react-script": "2.1.5" to "react-script": "2.1.8" (https://app.snyk.io/test/npm/react-scripts/)
**Before**
---
**js-yaml (HIGH)**
More about this issue: https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129 
**handlebars (HIGH)**
More about this issue: https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-174183
**js-yaml (MEDIUM)**
More about this issue: https://app.snyk.io/vuln/SNYK-JS-JSYAML-173999
**After**
---
1.  Delete frontend/node_modules folder
2.  Run docker-compose up
3.  Verify …
=> [Vulnerability Patch] Fixed 2 high and 1 medium vulnerabilities

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/css/cat-theme.css
Changed formatting of the reply buttons to more closely match the style shown in the design docs.
NOTE1: IE does not recognize ":focus-within", (but most other browsers support it) so it does not get the outline when one of the radio buttons has focus:
NOTE2: There is a minor glitch where there is no email type if you submit a response without making changes. This already exists on master and is not introduced by this PR. See https://trello.com/c/BLrOPCJC/48-bug-fix-reply-not-defaulting
1.  Start the eMIB test (Start eMIB -> Pre-test -> Start Test)
2.  Switch to the Inbox tab
3.  "Add email response"
4..  Verify that the buttons look as expected and change as expected
Applicable …
=> [Email Reply/Edit] Reply button formatting

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/tests/components/eMIB/ActionViewEmail.test.js, frontend/src/tests/components/eMIB/ActionViewTask.test.js, frontend/src/text_resources.js
I used the _PopupBox.jsx_ and _SystemMessage.jsx_ components to create a delete confirmation dialog when you want to delete an email response and / or a task.
**Email Response Delete Confirmation:**
**Task Delete Confirmation:**
4.  Add an email response and a task.
5.  Try to delete both of them and make sure that the popup dialog is looking good and working well, meaning that it does what it is supposed to do.
=> [Delete Response Confirmation] Added delete confirmation popup for email response and task

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx
Added a visible character counter to the bottom of the four text areas in EditEmail and EditTask
Add Email Response:
Add Task:
1.  Start eMIB/Start Test
2.  Open the Inbox tab
3.  Add an email
4.  Type in the Response and Reasons textareas
5.  See character count change
6. Repeat for Add Task
=> [Inbox] Adding visible text counter to EditEmail/Task dialog

frontend/src/components/eMIB/EmailPreview.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/css/inbox.css
This changes in this PR are fixing the following bugs:
- Gap at the top of the email preview list
- Email preview keyboard navigation
**Gap Bug**
---
**Before:**
**After:**
**Keyboard Navigation Bug**
---
**Mouse Over and Keyboard Focus:**
4.  Make sure the the gap bug is fixed.
5.  Also, make sure that you are able to navigate in the email preview list using the keyboard and everything look good (mouse over and focus).
=> [Bug Fixes] Fixing Email Preview Gap and Keyboard Navigation

frontend/src/store-index.js
Fixes a console warning caused by previous merges.
This may have been introduced when we updated dependencies to fix vulnerabilities
Console before:
Console after:
1.  Start project-thundercat
2.  See no more warnings in the console
=> [Bug Fix] Fixing history console warning

frontend/src/components/eMIB/EditTask.jsx, frontend/src/css/inbox.css, frontend/src/text_resources.js
The tooltip icons were already in the **Add Task** form, but they were static, so I added the tooltips content using _react-OverlayTrigger_ and _react-Popover_ libraries.
**Task Tooltip (EN):**
**Task Tooltip (FR):**
**Reasons For Action Tooltip (EN):**
**Reasons For Action Tooltip (FR):**
3.  Open the Inbox tab.
4.  Click on Create a task.
5.  Make sure you are able to see the tooltips when navigating using the keyboard and when clicking on the icons.
=> [Add Task] Added Tooltips in 'Add Task' form (new version)

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/text_resources.js
I implemented new cancel confirmation messages for the following situations:
- While creating a new email response or a new task and you hit the close button or click next to the response dialog
- While editing an new email response or a task and you hit the close button or click next to the response dialog
**New Email Response or Task**
---
**When you click one of the following places:**
**It shows the following:**
**If you click 'Return to response:'**
**If you click 'Cancel response:'**
**Edit Email Response or Task**
---
**Exactly the same behavior:**
4.  Create a new email response or …
=> [Cancel Response Dialog] Added cancel 'edit dialog' for inbox responses

frontend/src/components/eMIB/Evaluation.jsx
Removing hyperlink from the evaluation page
Before:
After:
Before:
After:
1.  Go to Evaluation before test and in test
2. See that hyperlink is no longe there
=> [QA Fix 5] Remove Hyperlink form Evaluation

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailContent.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js, frontend/src/tests/components/eMIB/Email.test.js, frontend/src/tests/components/eMIB/EmailContent.test.js, frontend/src/text_resources.js
Add the original email to the action dialog, so that when adding an email or task candidate has access to the email.
Paired with @MichaelCherry and @fnormand01 
1.  Go to the inbox.
2.  Click add email or add task and see the original email if you scroll down in the dialog.
=> [Inbox] Add original email to the action dialog

frontend/src/components/eMIB/EditTask.jsx
I added two states (_taskTooltipIcon_ and _reasonsForActionTooltipIcon_) in order to control the tooltip icon to display according to the tooltip focus.
**Task Tooltip Focused:**
**Reasons For Action Tooltip Focused:**
**Both Tooltip Icons are not Focused:**
4.  Click on _Create a task_.
5.  Click on the tooltip icons and make sure that the icons are changing as expected.
=> [Task Tooltips] Added states to control the tooltip icons

frontend/src/text_resources.js
Putting numbers in headings is confusing when you hear it from a screen reader. 
1.  Go to test instructions.
=> [Accessibility] Remove numbers for h headings

frontend/src/components/commons/ConfirmStartTest.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/text_resources.js
Remove unnecessary warnings from dialogs, in particular the start test and the submit test. I've added the content to the dialogs in paragraphs. 
1.  Start the test.
2.  Submit the test.
=> [Accessibility] Remove unnecessary warnings from dialogs

Dockerfile.dev, backend/backend/settings.py, backend/entrypoint.sh
This does 2 important things for our server setup:
- Creates a "production-ready" version of a docker file to be used on dev (but can also be used on test, prod, etc) instead of serving the JS in a node container.
- Sets up environment variables to manage "secret" information about the static PostgreSQL database, and defaults the dev database to what we have today. These variables will be injected to the docker containers at runtime via Azure -> App Service -> Application Settings.
The database locally will remain virtual locally so that developers can manage their own migrations and experiment with changes in a safe environment. 
Each server environment will have environment variables (stored in Azure), that set the respective database. (See `settings.py` change) This is important …
=> Setup server-ready version of application with Docker

frontend/src/components/eMIB/EmibTabs.jsx
I simply updated the _currentTab_ value in _EmibTab.jsx_ component in order to display the instructions tab first instead of the background tab.
**First thing you see when you start the eMIB test:**
2.  Make sure that the first page is the instructions tab.
=> [Emib Tabs] eMIB test is now starting on instructions tab, not background tab

frontend/src/components/commons/TestFooter.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/tests/components/commons/TestFooter.test.js
I added a toggle functionality in _TestFooter.jsx_ component that allows us to display two different test footers depending on the **testIsStarted** flag.
If **testIsStarted** is set to false, it should show the _Start test_ button.
If **testIsStarted** is set to true, it should show the _Quit test_ and _Submit Test_ buttons.
**Note that if you put the _testIsStarted_ flag to false, the _Start test_ button does nothing. An action will be added to this button in a future PR.**
**_testIsStarted_ is set to false:**
**_testIsStarted_ is set to true:**
**- this functionality can be tested by changing the _testIsStarted_ flag in _Emib.jsx_ component, where the _TestFooter.jsx_ component is …
=> [Test Footer] Adding test footer toggle functionality

frontend/src/components/commons/Tab.jsx, frontend/src/tests/components/commons/Tab.test.js
I added a disabled functionality that will allow us to disable tabs using props.
However, this functionality is not used yet. It'll be use soon in another PR.
**Here is an example of what the disabled button look like:**
**If you want to test that functionality, you have to add the following props in _TabNavigation.jsx_ component where the _Tab.jsx_ component is used:**
- `disabled={false}`
- `disabled={true}`
- or just don't put any disabled prop (that will make the tab enabled)
**Example:**
=> [eMIB Tabs] Added disabled functionality to Tab component

frontend/src/components/eMIB/EditActionDialog.jsx
Add action dialog should not be close-able by clicking backdrop.
N/A
1.  Go to inbox.
2.  Click add email.
3. Try clicking the backdrop outside the dialog to close.
=> [Inbox] Add action dialog should not be close-able by clicking backdrop

frontend/src/components/eMIB/Email.jsx
Move action buttons to after the original email. This is helpful for a screen reader because it's a bit more logical, and it ensures that keyboard focus after closing a dialog is on the added emails.
It also ensures the page is scrolled down when a new email gets added.
1.  Go to inbox.
2.  Select an email and notice action button location.
=> [Inbox] Move action buttons to after the original email

frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/text_resources.js
Make the multi-level org chart a nested tree - better for accessibility.
1.  Go to the background page and click image description.
=> [Background] Org chart as a nested list

frontend/public/index.html, frontend/src/App.js, frontend/src/Home.jsx, frontend/src/Prototype.jsx, frontend/src/Status.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/text_resources.js
Add HTML title tags anytime a page changes.
1.  Go to any page.
2.  Inspect element and look for the title element.
3.  Change pages and notice it update.
=> [Accessibility] Add HTML title tags

frontend/src/components/commons/Tab.jsx, frontend/src/text_resources.js
Add a tooltip for disabled tabs.
1.  Go to the sample test.
2.  Hover over a disabled tab.
=> [eMIB] Tooltip on disabled tabs

frontend/src/App.js, frontend/src/components/commons/LoginButton.jsx, frontend/src/components/commons/Translation.jsx, frontend/src/text_resources.js
This PR is adding the Login/Logout buttons in the nav bar with basic functionalities. It only switches the state of the login/logout buttons when you click on it.
Other actions will be added to these buttons in future PRs.
**Default View:**
**After clicking on _Login_:**
1.  Run the app.
2.  Make sure that the buttons are switching when clicking on it.
=> [Login / Logout] Adding login/logout buttons in the nav bar

frontend/src/App.js, frontend/src/components/commons/LoginButton.jsx, frontend/src/modules/LoginRedux.js, frontend/src/modules/index.js, frontend/src/tests/modules/LoginRedux.test.js
This PR is introducing the login states with Redux, so we'll be able to control what we want to display depending on the candidate's login state.
**I used the following console.log to demonstrate the operation of the login states using Redux**
**If logged out:**
**If logged in (after clicking on _Login_ button):**
**- To test that functionality, you would have to do the exact same thing I did in the screenshots, meaning that you would need to add a _console.log_ to make sure that the login states are working as expected.**
=> [Login / Logout] Introducing login states with Redux

frontend/src/App.js, frontend/src/Dashboard.jsx, frontend/src/css/cat-theme.css, frontend/src/tests/Dashboard.test.js, frontend/src/text_resources.js
This PR is adding the _Dashboard_ link in the nav bar and its content. This _Dashboard_ component is also using the _loggedIn redux state_ in order to display a description depending on the login states.
**If logged out:**
**If logged in (after clicking on _Login_ button):**
1.  Open the _Dashboard_ link.
2.  Make sure that the description is changing if you click on the _Login_ button.
=> [Dashboard] Adding dashboard link in nav bar

frontend/src/components/eMIB/Inbox.jsx, frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/components/eMIB/Inbox.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js
Preserving current email in inbox redux rather than inbox state
Select 2nd email:
Change Tab:
Change back:
1.  Enter the test, open an email (other than the first)
2.  Change tabs
3.  Change back to Inbox, see that same email is open
=> [Inbox] Save current email when changing tabs

frontend/src/components/commons/Notepad.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/components/eMIB/SideNavigation.jsx, frontend/src/components/eMIB/constants.js
Replacing eMIB tabs with reactbootstrap tabs for accessibility purposes. 
Still need to in future prs:
- replace tabs on logins
- delete custom tabs
- add "disabled" tooltips to the boostrap tabs
- have a pairing session with joey
1.  Navigate through the sample test.
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ using a component library that's already tested
=> Replace tabs with Bootstrap tabs

frontend/src/components/commons/Notepad.jsx, frontend/src/components/commons/TestFooter.jsx, frontend/src/components/eMIB/EmailPreview.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/css/cat-theme.css
Updates to visuals of the emib tabs from a pairing session with @joeyhua 
1.  All visual changes in the sample test.
=> Dev/Design Pair: Emib tabs

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditTask.jsx
Where we have tab indexes is causing problems so removing them for now.
no visual change.
Shouldn't tab into examples anymore.
=> Accessibility - remove tab indexes

frontend/src/components/eMIB/SideNavigation.jsx
Add tab index to the center column of content - this means you can tab to the content once selecting the side navigation. 
No visible changes.
1.  go to the sample test
2. tab to the side nav and select an option
3. the next time you tab should take you to the main text content.
=> [Instructions and background] Add tab-index to main content

frontend/src/components/commons/PopupBox.jsx
This PR is adding two new _props_ in **PopupBox** component. These new _props_ allow us to display or not the close button in the top right corner and allow us to set the **backdrop** to true or false (if set to true, you will not be able to close the popup box by clicking outside of it).
Here is an example that shows how to use it:
These new _props_ will definitely be helpful in future PRs.
**isCloseButtonVisible set to _false_:**
**isCloseButtonVisible set to _true_ or isCloseButtonVisible prop not present:**
**isBackdropStatic set to true (cannot close popup by clicking outside of it):**
**isBackdropStatic set to false or prop not present (can close popup by clicking outside of it):**
Manual …
=> [PopupBox] Added new props for additional customization purposes

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/tests/components/eMIB/ActionViewEmail.test.js, frontend/src/tests/components/eMIB/ActionViewTask.test.js, frontend/src/tests/components/eMIB/EditActionDialog.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js
Fixing the bug where an empty email response will not render in the preview; cannot be edited; and where an empty task cannot be edited.
N/A
1.  Add an empty email and task
2.  Verify that you can preview both without a crash
3.  Verify that you can edit both without a crash
=> [Bug Fix] Empty response patch

frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailContent.jsx, frontend/src/text_resources.js
Remove unnecessary headings in the original email, action view email and action view task. These were really hard to navigate with a screen reader.
1.  Go to the sample test.
2. See examples in the instructions
3. See emails in the inbox (original, and ones you add)
=> [Accessibility] Remove unnecessary headings

frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailPreview.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/tests/components/eMIB/EmailPreview.test.js, frontend/src/tests/components/eMIB/Inbox.test.js
Change inbox navigation to be closer to the current implementation of side navigation. This makes the navigation consistent throughout the simulation. 
1.  Go to the inbox.
2.  Navigate between emails using the arrow keys, and press tab to get to the email content.
=> [Accessibility] inbox navigation 

frontend/src/components/commons/TreeNode.jsx, frontend/src/css/lib/tree.css
Cleanup CSS of org chart and default the chart to be expanded.
1.  Go to background page.
2.  Open image description dialogs.
=> Org chart cleanup - css and default expanded

frontend/src/components/commons/Notepad.jsx
Notepad toggle needs to be one button so that the keyboard focus is never null. It was suggested to use aria-pressed to build this toggle: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
There are no visual changes.
1.  Go to sample test.
2.  Navigate to the keyboard using tabs. Press enter to toggle the notepad.
=> [Accessibility] Notepad toggle should be one button

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js
Added logic to check if the if the action in the prop is for an email. of so, and if the emailType is not defined, then default to reply.
Added tests to ensure the default is properly set (this test fails on master)
Added tests to ensure that if a email type is provided, it is not overriden.
Create a new email:
Save immediately with  no changes:
See that it defaults to reply:
1.  Start eMIB -> Pre test instructions -> Start test
2.  "Add email Response"
3.  "Save response" without making any changes
4.  View the email reply
5.  **See that there it now defaults to reply**
=> [Bug Fix] Default email type

frontend/src/css/cat-theme.css
Changing disabled danger button color to improve contrast.
WIP as the contrast seems worse
Before:
After:
1. Start the test
2.  Quit the test
3.  See that the disabled quit button is a different color
=> [Accessibility] Adding override for btn-danger:disabled

frontend/src/components/eMIB/CollapsingItemContainer.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/components/eMIB/EmailContent.jsx, frontend/src/css/cat-theme.css
Move email to the top of the action dialog and put it in a collapsing container.
1.  Go to the sample test and navigate to the inbox.
2.  Select an email and add a response.
3.  Notice the location of the original email.
=> [Inbox] Move email to top of action dialog

frontend/src/components/eMIB/EditTask.jsx, frontend/src/tests/components/eMIB/EditTask.test.js
Fix character counter on tasks reasons for action - it previously displayed text instead of a count.
1.  Create a task.
2.  Start typing reasons for action and notice char count changing.
=> [Bug fix] char counter on task reasons for action

frontend/src/components/authentication/LoginForm.jsx, frontend/src/components/authentication/RegistrationForm.jsx
This PR is linking all the Login and Registration labels to their respective fields.
(N/A)
1.  Open the Login and Registration forms.
2.  Click on each labels and make sure that they are linked to their respective fields.
=> [Accessibility] Linking login and registration labels to their respective fields

frontend/src/components/commons/Notepad.jsx
Since the text on the button updates, aria-pressed attribute no longer makes sense.
N/A
1.  Toggle notepad with a screenreader open.
=> [emib] Remove aria-pressed on notepad toggle

frontend/src/components/authentication/LoginForm.jsx, frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/css/registration-form.css, frontend/src/text_resources.js
This PR is linking all the Login and Registration form errors to their respective fields. I also updated the aria-labels, so that screen reader users get a description of the fields requirements.
**Login Form (without error):**
**Login Form (with errors):**
**Registration form (without error):**
**Registration form (with errors):**
1.  Start NVDA.
2.  Navigate in the Login and Registration forms using the keyboard and make sure that you get all the needed information (invalid fields, required fields, etc.) from the screen reader.
=> [Accessibility] Linking login and registration form errors to their respective fields

frontend/src/components/commons/LoginButton.jsx
Hiding the _Login_ button (top right corner button) if the current page is login page, in order to avoid confusion.
**If not logged in - Home/Login Page:**
**If not logged in - eMIB Sample Test Page:**
**If logged in - Home/Dashboard Page:**
**If logged in - eMIB Sample Test Page:**
- Navigate in the application and make sure that the Login/Logout button is displayed at the right time.
=> [Accessibility] Hide login button if current page is login page

frontend/src/components/authentication/LoginForm.jsx
I simply removed the unneeded aria-label from the login form.
(N/A)
1.  Open the login form from the home page.
2.  Navigate using the screen reader and make sure that you get the expected behavior when you enter valid and invalid credentials.
=> [Accessibility] Removing unneeded aria-label from login form

frontend/src/components/commons/PopupBox.jsx
Update of styles for CAT dialogs.
Before
After
1.  Try out the dialogs by starting the test, submitting, seeing settings, org chat, etc.
=> Update styles for CAT dialogs

frontend/src/components/eMIB/EditActionDialog.jsx
Update styles of action dialogs
Before
After
1.  Go to inbox.
2.  Click add email or add task.
=> [Inbox] Update styles of action dialogs

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/text_resources.js
Add tooltips to the add email and add task dialogs. (We had something similar before, but I broke them with the icon change.)
1.  Go to the inbox.
2.  Add an email and add a task. Click on the "?" to see tooltips.
=> [Inbox] Add tooltips to action dialogs

frontend/src/components/commons/Settings.jsx, frontend/src/text_resources.js
Added content for the settings dialog. French will come once it's finalized and translated.
1.  Click on the settings button in the nav.
=> Setting dialog content

frontend/src/components/commons/PopupBox.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/Email.jsx
When HTML elements are used for layout or formatting, the screen reader picks up on them in unexpected ways. This PR removes extra elements and uses CSS to handle styling and spacing.
1.  Go the the inbox with a screen reader.
2.  Add an email and select the radio buttons.
=> [Accessibility] Use CSS instead of extra elements to space components

frontend/src/components/eMIB/CollapsingItemContainer.jsx
Make collapsing component accessible. 
Guide I used: https://inclusive-components.design/collapsible-sections/ 
1.  Go to the inbox with a screen reader.
2.  Click add a task and navigate to the original email expanding section.
=> Make collapsing component accessible

frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/text_resources.js
This PR is introducing a fix for the "password is too similar to username" error.
**Initial form view:**
**Trying to create a new account with a password similar to the username (username: password.normand@email.ca, password: Password1!):**
2.  Try to create a new account with a password similar to the username and make sure that you get the right error(s).
=> [Bug Fix] Fixing password is too similar to username bug

frontend/src/components/authentication/RegistrationForm.jsx
Fixed a small bug related to the _privacy notice_ link that opens a popup box in registration form.
Before, we were not able to open the privacy notice popup with the keyboard, but now we can.
(N/A)
1.  Open the registratinon form.
2.  Navigate using the keyboard and make sure that you can open the privacy notice popup box..
=> [Bug Fix] Fixing the 'privacy notice' popup access using the keyboard

.travis.yml, backend/tests/postman/ThunderCAT.postman_collection.json
This PR is introducing new travis configurations. These new settings are creating a superuser using command line, so we we are now able test APIs that need admin rights. I also updated the postman tests that needed these rights to succeed.
(N/A)
- It's not really testable. You can take a look at the travis console log to see how it works.
=> [Travis Configs] Creating Django superuser via commands for Travis tests (for future API tests)

backend/config/urls.py, backend/views/test_instructions_view.py, backend/views/test_questions_view.py
Adding view and url registration of test-instructions API
Accessing `http://localhost/api/test-instructions/?test_name=emibSampleTest` when logged in
Accessing `http://localhost/api/test-instructions/?test_name=emibPizzaTest` when logged in as admin
Accessing `http://localhost/api/test-instructions/?test_name=emibPizzaTest` when not logged in
=> [Test API] Adding instructions view

backend/config/urls.py, backend/views/test_instructions_view.py, backend/views/test_meta_data_view.py, backend/views/test_questions_view.py
Adding view and url registration of test-meta-data API
Accessing `http://localhost/api/test-meta-data/?test_name=emibSampleTest` when logged in
Accessing `http://localhost/api/test-meta-data/?test_name=emibPizzaTest` when logged in as admin
Accessing `http://localhost/api/test-meta-data/?test_name=emibPizzaTest` when not logged in
=> [Test API] Adding meta-data-api view

backend/tests/postman/ThunderCAT.postman_collection.json
This PR is introducing new postman tests related to the following APIs:
- test meta data APIs (sample and pizza tests)
- test instructions APIs (sample and pizza tests)
- test questions APIs (sample and pizza tests)
- This is not really testable. However, you can take a look at _travis_ console logs to see the new added tests.
=> [Postman Tests] Adding postman tests for new content APIs

frontend/src/modules/EmibInboxRedux.js, frontend/src/tests/modules/EmibInboxRedux.test.js
Loading EN/FR from state of redux rather than the json file
This will be needed later when loading from DB rather than json so that we do not need to ping the DB every time we toggle language, just once when loading the test
No change in behavior
Enter the Emib
Look at the questions
Ensure that the language toggles as expected
=> [Test Structure] Load en/fr from state rather than json

frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/text_resources.js
This PR is introducing part of the new candidate registration flow. It means that when a new user creates an account, he gets redirected to the dashboard page logged in.
**Creating a new account:**
**After clicking on _Create account_ button:**
1.  Create a new account with the registration form.
2.  Make sure that you are logged in and you get to the dashboard page when clicking on _Create account_ button.
=> [Registration Flow] Candidate registration flow updates

frontend/src/components/authentication/RegistrationForm.jsx
This PR is introducing some accessibility fixes after David's feedback on the registration form. The following updates have been done:
- remove tooltip tab selection
- make the screen reader read the tooltip content on year field selection
- add aria-describedby to password field, so it reads the password requirements on password field selection
(N/A)
1.  Start NVDA.
2.  Open the registration form.
3.  Make sure that the tooltip content is read by the screen reader when you select the _year_ DOB field.
4.  Also, make sure that you get the password requirements from the screen reader on password field selection.
=> [Accessibility] Registration form accessibility updates

frontend/src/components/authentication/AuthenticationTabs.jsx
This PR is fixing the IE login/registration forms bug. Before the forms were not centered. Now they are.
**Before:**
**After:**
1.  Open the login and/or the registration form.
2.  Make sure that the forms are centered.
=> [Bug Fix] Fixing IE login form bug

frontend/src/App.js
This PR is only adding the status page as allowed url without any authentication. So any users have now access to status page (http://localhost/status), even if they are not authenticated.
(N/A)
1.  Use the following url to access to status page: http://localhost/status.
2.  Make sure that you have access, even if you are not authenticated.
=> [Status Page] Added status page as allowed url without authentication

frontend/src/App.js, frontend/src/text_resources.js
Updated the wording of the _Home_ link:
- When not authenticated, the name of this link is: Home
- When authenticated, the name of this link becomes: Your tests
**When not authenticated:**
**When authenticated:**
1.  First, make sure that this link is displayed as _Home_.
2.  Login to the system.
3.  Then, make sure that this link is displayed as _Your tests_.
=> [Home Link] Updated the wording of the Home link

frontend/src/App.js, frontend/src/components/authentication/LoginForm.jsx, frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/components/commons/ContentContainer.jsx, frontend/src/components/commons/TestFooter.jsx, frontend/src/components/eMIB/EmibIntroductionPage.jsx, frontend/src/components/eMIB/EmibTabs.jsx, frontend/src/components/eMIB/Evaluation.jsx, frontend/src/components/eMIB/Inbox.jsx, frontend/src/components/eMIB/OrganizationalInformation.jsx, frontend/src/components/eMIB/SideNavigation.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/components/eMIB/TestInstructions.jsx, frontend/src/components/eMIB/TipsOnTest.jsx
This PR is introducing aria landmarks and sections/regions for screen reader users. If I missed parts of our app that need that, please let me know.
(N/A)
1.  First, you'll need to launch NVDA.
2.  Navigate throughout the app using the screen reader and make sure that everything is working as expected.
=> [Accessibility] Adding landmarks and regions

frontend/src/components/authentication/RegistrationForm.jsx
This PR is introducing new DOB fields updates. These changes are related to David's comments. Here is a summary of the changes:
- Removed the DOB label from the aria-label of the month and year fields
- Updated tool tip display conditions (displayed on focus or on year field focus)
- Updated tool tip button style
**Displays the tool tip on year field focus:**
**Hides the tool tip on year field blur:**
**Tool tip is also displayed on '?' focus (the same way it was before):**
2.  Navigate using the keyboard and make sure that the tool tip is displayed on year field focus and hidden on year field blur.
3. Make also sure that …
=> [Accessibility] Registration form dob fields update to respect all the accessibility aspects

frontend/src/components/authentication/RegistrationForm.jsx
This PR is introducing the a new tool tip for the password. This tool tip is displaying the password requirements.
**Password Tool Tip:**
2.  Make sure that you are able to see the password's tool tip when you click on '?'.
- [] ~~I have researched WCAG2.1 accessibility standards and met them in this PR (can be navigated using a keyboard)~~
=> [Accessibility] Adding password requirements inside a tool tip

frontend/src/modules/LoadTestContentRedux.js, frontend/src/modules/index.js, frontend/src/testDefinition.js
This PR is introducing a new Redux Module called _LoadTestContentRedux_. This module will be useful to get the test content using the new APIs created in the previous PRs.
This PR is only introducing the actions to get the test meta data and update the redux state.
**How to use these new actions:**
**Then if we print the redux state called 'testMetaData':**
**We get that result:**
- you can test these new actions using the code shown above in any desired file of the project. You'll just need to assure the redux connection with this selected file.
=> [Test Meta Data] Getting test meta data from the back end

frontend/src/modules/EmibInboxRedux.js, frontend/src/modules/sampleEmibJson.js, frontend/src/tests/components/eMIB/Inbox.test.js, frontend/src/tests/modules/EmibInboxRedux.test.js
This PR simply restructures the json to match the return for #359. When both of these are merged in, we can simply swap out the json for the DB without needing to change the rest of the code or the tests (as those changes are in this PR)
This results in no visible changes
Interact with the test, namely the inbox, and make sure it acts as expected. There should be no change in functionality
=> [Test Structure] Update json emails to match db

frontend/src/components/authentication/RegistrationForm.jsx
This PR is introducing a new function called _focusOnHighestErrorField_. This function find the highest error field in registration form (if there is any) and focus on it.
**Initial View:**
**Error on _Last name_ and email fields:**
**As soon as I click on _Create account_ button, it focuses on the highest error field:**
**Once fixed, if I click again on _Create account_ button, it focuses on the highest error field again:**
2.  Fill out the form, but put intentional errors.
3.  Click on _Create account_ button and make sure the it focuses on the highest error field.
=> [Accessibility] Focusing on highest registration form error field

frontend/src/components/authentication/RegistrationForm.jsx
This PR is removing all multiple `<label>` elements associated to the same input. These multiple elements were associated to the following fields/inputs:
- First name
- Last name
- Email
- Password
- Password confirmation
- Privacy notice
(N/A)
1.  Launch NVDA.
2.  Navigate in the registration form using the screen reader and make sure that you get the right description for each field (with and without error).
=> [Accessibility] Removing multiple label elements from registration form

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/tests/components/eMIB/EditActionDialog.test.js, frontend/src/text_resources.js
Max character count on inputs should be accessible by:
- providing the limit in the label
- alerting the screen reader when the limit is reached
1.  Go to inbox with a screen reader.
2. Add an email or task and hit the max limit.
3. Listen for alert.
=> [Inbox] Character limit should be accessible

frontend/package.json, frontend/src/components/eMIB/BackgroundInformation.jsx, frontend/src/components/eMIB/markdown_files/BackgroundInformation_en.md, frontend/src/components/eMIB/markdown_files/BackgroundInformation_fr.md, frontend/src/text_resources.js, frontend/yarn.lock
This PR is introducing a new package called 'react-markdown' (https://github.com/rexxars/react-markdown). This package is useful to use markdown files as application content files.
This PR is also introducing the usage of markdown files instead of LOCALIZE strings to populate the background information part of the background content.
**Old Version - localize strings (EN):**
**Old Version - localize strings (FR):**
**New Version - markdown files (EN):**
**New Version - markdown files (FR):**
1.  Launch the eMIB Sample Test.
2.  Start the test.
3.  Select the _Background_ tab.
4.  Make sure that you get the content when you select _Background Information_ on the …
=> [Test Content Definition - Background] Using markdown files for Background Content (1)

frontend/src/components/authentication/RegistrationForm.jsx
Fixes: `Line 1014:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank`
=> Make links in privacy notice safe

frontend/src/components/eMIB/OrganizationalInformation.jsx, frontend/src/components/eMIB/markdown_files/OrganizationalInformation_en.md, frontend/src/components/eMIB/markdown_files/OrganizationalInformation_fr.md, frontend/src/text_resources.js
This PR is introducing the usage of markdown files instead of LOCALIZE strings to populate the Information about the Organizational Development Council (ODC) part of the background content.
**Old Version - localize strings (EN):**
**Old Version - localize strings (FR):**
**New Version - markdown files (EN):**
**New Version - markdown files (FR):**
1.  Launch the eMIB Sample Test.
2.  Start the test.
3.  Select the _Background_ tab.
4.  Make sure that you get the content when you select _Information about the Organizational Development Council (ODC)_ on the side navigation menu.
=> [Test Content Definition - Background] Using markdown files for Background Content (2) 

frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/components/eMIB/sample_test_markdown/TeamInformation_section1_en.md, frontend/src/components/eMIB/sample_test_markdown/TeamInformation_section1_fr.md, frontend/src/components/eMIB/sample_test_markdown/TeamInformation_section2_en.md, frontend/src/components/eMIB/sample_test_markdown/TeamInformation_section2_fr.md, frontend/src/text_resources.js
This PR is introducing the usage of markdown files instead of LOCALIZE strings to populate the Information about the Information about the Quality Assurance (QA) Team part of the background content.
However, we still have to figure out how to introduce markdown files for the image description of this section.
**Old Version - localize strings (EN):**
**Old Version - localize strings (FR):**
**New Version - markdown files (EN):**
**New Version - markdown files (FR):**
1.  Launch the eMIB Sample Test.
2.  Start the test.
3.  Select the _Background_ tab.
4.  Make sure that you get the content when you select Information about the Quality Assurance (QA) Team on the side navigation menu.
=> [Test Content Definition - Background] Using markdown files for Background Content (4)

frontend/src/App.js, frontend/src/text_resources.js
Adding alt text to logo. See screenshots
1.  Look at the alt text for the in-test and out-of-test logos
=> [Accessiblity] Fix alt text for logo

frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/components/commons/Settings.jsx
Recommendation from @fnormand01 in previous PR
Add sections around long content like in the privacy notice and settings dialog.
1.  View settings or privacy notice with a screen reader and skip content.
=> [Accessibility] Add sections for settings and privacy content

frontend/src/components/commons/QuitTest.jsx, frontend/src/text_resources.js
- Content update on the quit test dialog.
- Bug fix: Go to the test in english, open quit test dialog, close it, switch languages, notice the checkboxes are still in english.
1.  Go to the sample test and open the quit dialog in both languages.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> [Content update/bug fix] Quit test dialog

frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/components/commons/Settings.jsx
Change text to close dialogs from okay to close on the privacy and settings dialogs.
- Bug fix (non-breaking change which fixes an issue
=> [Content update] Convert okay buttons to close buttons

frontend/src/components/commons/Notepad.jsx
Adding aria-placeholder to the notepad
English:
French:
=> [Accessibility; Notepad] Adding aria-placeholder to notepad

frontend/src/components/commons/ContentContainer.jsx
Changing image role from banner to presentation.
Based on a few resources:
- role=presentation is supported in all major browsers, JAWS, NVDA, and IE 11
- role=none is supported by JAWS and most major browsers (but not NVDA or IE 11)
- Narrator in Windows supports none of the above.
Resources:
https://codepen.io/stevef/post/none-or-presentation
https://github.com/w3c/aria-practices/issues/515
Look at the image role in the dev tools
=> [Accessibility] Switching from banner to presentation

frontend/src/components/commons/PopupBox.jsx, frontend/src/components/eMIB/EditActionDialog.jsx
Hrs are read out by screen readers as "blank" - this is really annoying. We should replace them with CSS borders. This PR does that for our dialogs.
1.  Open any dialog on the site with a screen reader.
=> [Accessibility] Remove hr from dialogs and replace with styling

frontend/src/components/eMIB/EditEmail.jsx
Remove underline from radio button text because it's not a link and causes problems for accessibility.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> [Accessibility] Remove underline from reply replyall forward

frontend/src/components/authentication/LoginForm.jsx, frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/components/commons/PopupBox.jsx, frontend/src/components/commons/Settings.jsx, frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx
Fix h tags on the home page, login and accounts, and dialogs. There should always be a h1, and numbers should not be skipped.
This does change the appearance of some areas of our application because H1 is bigger than H2.
1.  Go to home page and notice headings with a screen reader.
2.  Open dialogs and notice headings with a screen reader.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> [Accessibility] H tags should be in number order

frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/text_resources.js
PR to add aria-labels to the image descriptions
Note: I prefixed the French translations with FR, since I was guessing at the translation.
EN OCD Chart:
FR OCD Chart
EN QA Chart
FR QA Chart
Open NVDA
Enter the eMIB sample
Tab to the Image Descriptions buttons in the background tabs
=> [Accessibility Patch] Adding aria-labels to image description buttons

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx, frontend/src/tests/components/eMIB/EditTask.test.js
If a new email/task is created and saved (without any edits), when it is opened for editing, an error is thrown. This adds logic in state to default to an empty string when not defined.
This fixes:
- Email's emailBody
- Email's reasonsForAction
- Task's task
- Task's reasonsForAction
=> [Bug Fix] Fix error when editing empty email/task

frontend/src/components/commons/TreeNode.jsx
Changes behavior of tree nodes to be collapsed by default; seems to fix issues David caught
Interact with either org chart, see that the tree noded work as expected
=> [Accessible Org Charts] Collapsed Tree Nodes

frontend/src/components/eMIB/BackgroundInformation.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/EmibIntroductionPage.jsx, frontend/src/components/eMIB/OrganizationalInformation.jsx, frontend/src/components/eMIB/OrganizationalStructure.jsx, frontend/src/components/eMIB/TeamInformation.jsx, frontend/src/modules/LoadTestContentRedux.js, frontend/src/tests/modules/LoadTestContentRedux.test.js
We called the API in each component. Instead, we should call it once, load everything into redux, and then have everything connected to redux.
This PR also removes a call for instructions from redux because that is not loaded from the backend so the code was never called.
I didn't fix everything I'd like to, including some naming, but this PR is big enough.
Before
After
1.  All background and overview pages should have content when navigating through the test.
=> Frontend redux refactor to reduce API calls

frontend/src/App.js
Fixes bug introduced by #442 where accessing `localhost` renders the following, rather than redirecting to `http://localhost/login`. Whether an auth_token is received or not, it uses the same logic to determine where to go:
Now redirects properly:
Go to `localhost`; verify that you are redirected to `localhost/login`
=> [Bug Fix] Fix home page redirect

frontend/src/Status.jsx, frontend/src/components/eMIB/ActionViewEmail.jsx, frontend/src/components/eMIB/ActionViewTask.jsx, frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/Email.jsx, frontend/src/components/eMIB/EmailContent.jsx
Replace HRs with borders in CSS on other elements.
I tried to follow all the comments from @joeyhua here: https://github.com/code-for-canada/project-thundercat/pull/443
1.  Go through sample test where there are hr lines and they should still be displayed the same.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> [Accessibility] Replace HRs with borders in CSS on other elements

frontend/src/components/eMIB/Inbox.jsx
This PR is introducing a fix related to the emails view when launching the Pizza Test.
**Before:**
**After:**
**Sample Test still looks the same too:**
1.  Launch the Sample/Pizza Test (See PR #461 for details on how to launch the pizza test).
2.  Make sure that the emails view is displayed as expected, meaning without any overflow bugs.
=> [Display Bug] Fixing emails view (Pizza Test)

frontend/src/components/eMIB/EditActionDialog.jsx, frontend/src/components/eMIB/EditEmail.jsx
Auto-fill in the `to` field based on the reply/replyall/fwd selection. This defaults to the reply field being selected.
1.  Go to the inbox.
2. Click "Add email response"
3. Should by default reply to whoever sent the email.
4. Selecting other email types should change recipients.
=> Feature - auto-fill the to field based on the reply/replyall/fwd selection

frontend/src/components/eMIB/Inbox.jsx, frontend/src/components/eMIB/SideNavigation.jsx
This PR is introducing a fix that allows us to scroll using keyboard arrows in test content (Instructions, Background Info, Emails Content).
(N/A)
1.  Launch the Sample Test.
2.  In each section of the test (Instruction, Background Info and Inbox), make sure that you are able to scroll up and down using the keyboard arrows.
=> [Accessibility] Fixing scroll using arrows bug

frontend/src/Home.jsx, frontend/src/components/authentication/LoginForm.jsx, frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/modules/LoginRedux.js, frontend/src/tests/modules/LoginRedux.test.js
This PR is simply fixing the display of 'Error' in the Home page bug. Before this fix, when we were refreshing the page, the page title was becoming 'Error - CAT Home', even if there was no error on Login and Registration forms.
So this PR contains the following changes:
- Renamed the state called _isRegistrationFormValid_ for _pageHasError_.
- Renamed the function called _updateIsRegistrationFormValidState_ for _updatePageHasErrorState_.
- Refactored the logic of the usage of this function/state.
**Before**
---
**When launching the app for the first time (everything was working as expected):**
**After refreshing the page (wrong behavior):**
**After**
---
**When launching the app for the first time:**
**When one of the forms is invalid …
=> [Accessibility] Fixing display of 'Error' in Home page title bug

frontend/src/App.js, frontend/src/Dashboard.jsx, frontend/src/components/eMIB/Emib.jsx, frontend/src/components/eMIB/EmibIntroductionPage.jsx
Link to the pizza test from the dashboard after a user logs in.
This is currently hard-coded for all candidates, but in the future we'll need to make this even more dynamic.
1.  Login.
2. Click on view test.
3. Go through the pizza test.
4. Go through sample test.
5. There should be no errors.
=> Link to pizza test from the dashboard

frontend/src/components/commons/ConfirmStartTest.jsx, frontend/src/modules/LoadTestContentRedux.js, frontend/src/text_resources.js
The start test dialog either displays the time allotted in minutes or "unlimited time" if no time is specified. 
1.  Go to the sample test instructions and click start test.
2.  Login and go to the pizza test instructions and click start test.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
=> [Start dialog] Display time allotted for the test.

frontend/src/components/authentication/RegistrationForm.jsx, frontend/src/text_resources.js
Adding "valid" next to check mark to further reinforce valid fields
With missing 2nd password:
With invalid date:
Open login page.
Fill out fields and see what the valid text appears
=> [Accessibility] Add supporting test to valid fields in login

frontend/src/Dashboard.jsx, frontend/src/components/commons/QuitConfirmation.jsx, frontend/src/components/eMIB/Background.jsx, frontend/src/components/eMIB/Confirmation.jsx, frontend/src/components/eMIB/EmibIntroductionPage.jsx, frontend/src/components/eMIB/InTestInstructions.jsx, frontend/src/components/eMIB/SideNavigation.jsx, frontend/src/modules/TestStatusRedux.js
This PR is introducing new focus management in the whole application. All pages where the focus was returning to the top navigation section are now keeping their focus.
Focus management of the following components have been updated:
- _Dashboard.jsx_
- _EmibIntroductionPage.jsx_
- _SideNavigation.jsx_
- _QuitConfirmation.jsx_
- _Confirmation.jsx_
Also, minor updates have been done to startIndex of _InTestInstructions.jsx_ and _Background.jsx_ components and "catLanguage" local storage is now removed on quit test action.
Once merged into master, I'll schedule a meeting with David to review these changes.
**Dashboard**
---
**Before, once logged in, the focus was on the table:**
**Now, the focus is on …
=> [Accessibility] Focus Management

frontend/src/components/eMIB/BackgroundSection.jsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
N/A
1.  Go to Background Information page.
2.  View Org charts in both languages.
~~[ ] I have added tests that prove my fix is effective or that my feature works~~
~~[ ] I have researched WCAG2.1 accessibility standards and met them in this PR (can be navigated using a keyboard)~~
=> Changed language variable in background org charts to constant

frontend/src/components/eMIB/EditEmail.jsx, frontend/src/components/eMIB/EditTask.jsx
Corrects tooltips to behave exactly like the tooltip for the Year DOB in the RegistrationForm
- Cannot tab to ? button
- ? can be clicked to toggle the tooltip
- Tooltip reads automatically (in NVDA) when a user tabs into the textfield
- Tooltip does not visibly open when user tabs into the field
- (new in ea161a4) Tooltip closes automatically when user tabs away from ?
No field selected
Tabbing into field (tooltip does not open, but NVDA reads it out loud):
Clicking on the ? button
Open NVDA
Open the test; create/edit an email or text response
Try out the behaviors listed in the description
=> [Accessibility] Tooltip Fix

frontend/src/components/eMIB/SideNavigation.jsx
This PR is fixing the broken side navigation. 
Before this fix, we needed to tab throughout the side navigation items, hit enter to select the desired item and then tab until the focus was on the content.
Now, you can navigate throughout the navigation items with up and down arrows and simply tab to go to the content part of the selected item.
**Select the desired side navigation item using up and down arrows:**
**Once the desired item is selected, hit tab once to focus on the content:**
1.  Start the eMIB sample test.
2.  Make sure that you can navigate throughout the side navigation items using up and down arrows.
3.  Also make sure that you can go to the content by hitting "Tab" once.
=> [Accessibility] Side navigation bug fix
