code-for-canada/project-thundercat

README.md

Documenting an issue we are having with line endings auto changing on windows, but docker being run on windows. The readme now outlines the temporary fix.
We are also considering runing `git config core.autocrlf false`, but have not made that work yet.

Documentation: Add known issue to readme

---

frontend/README.md
frontend/entrypoint.sh
frontend/package.json
frontend/src/App.test.js
frontend/src/setupTests.js
frontend/yarn.lock

To run a test, login to the docker container, and run `npm test` (documented in frontend/README.md).
Example of passing output:
Steps taken:
- installed enzyme package for testing
- added `yarn start` to entrypoint to keep docker container running
- added sample tests to app.test.js

Setup front end testing for react components 

---

.gitattributes
backend/README.md
backend/backend/test_views.py

In order to run the test, execute the following command from the backend container:
./manage.py test
Here is the result:

Created a first basic Python unit test

---

rm-docker-toolbox-setup.md

Adding documentation to list additional setup steps for use with DockerToolbox (Windows 7)

Documentation: additional steps when using docker-toolbox

---

rm-common-debugging.md

Added more details about the vpn conflict (and possible causes) and refered to the rm-docker-toolbox-setup, in case someone using docker tool box looks here first

Documentation: more details on vpn conflict and reference to rm-docker-toolbox-setup

---

frontend/package.json
frontend/src/index.js

App on IE 11 (PSC default browsers)

IE Fix: Installed a polyfill to allow app to run on IE

---

frontend/src/components/status/StatusCheck.test.js

We wrote these as a group, but for some reason they never made it into the last PR.

Unit tests: StatusCheck.jsx

---

frontend/src/components/status/SystemCheck.test.js
frontend/src/helpers/GetIeVersion.js

Fixed System Check Tests
**Tests**
---

(FIX) Status Page: Created System Status Table

---

nginx/nginx-proxy.conf

**Screenshots (before the fix)**
---
**Internet Explorer:**
**Google Chrome:**
**Firefox:**
**Screenshots (after the fix)**
---
**Internet Explorer:**
**Google Chrome:**
**Firefox:**
**Tests:**
---
**Reference:**
---
GitHub Link: https://github.com/socketio/socket.io/issues/1942

(FIX) Master Issue: Websocket Error

---

backend/README.md

**Description**
---
Added useful information related to Django migrations. 
Here are the main commands:
- _python manage.py makemigrations backend_
- _python manage.py migrate backend_
- _python manage.py showmigrations backend_
- _python manage.py migrate <migration_name> backend_
**Screenshot**
---

Django Migrations: Documentation

---

frontend/package.json
frontend/src/components/eMIB/Background.jsx
frontend/src/components/eMIB/Confirmation.jsx
frontend/src/components/eMIB/Emib.jsx
frontend/src/components/eMIB/HowTo.jsx
frontend/src/components/eMIB/Inbox.jsx
frontend/src/test/Background.test.js
frontend/src/test/Confirmation.test.js
frontend/src/test/Emib.test.js
frontend/src/test/HowTo.test.js
frontend/src/test/Inbox.test.js
frontend/yarn.lock

**Description**
---
With these changes, we are now able to switch between English and French languages in the Sample Test. To do so, I installed and used the _react-localization_ library.
Ref: https://www.npmjs.com/package/react-localization
**Screenshots**
---
**English version of the Home Page of the Sample Test:**
**French version of the Home Page of the Sample Test after selecting "Français":**
**Tests**
---

React Localization: Introduction

---

frontend/src/components/eMIB/Emib.jsx
frontend/src/test/Emib.test.js

Added check to determine the current page and look up the relevant text for the next button accordingly.
New French text has been prefixed with "FR"

Emib next button

---

frontend/src/App.css
frontend/src/App.js
frontend/src/Home.jsx

We had a bunch of CSS we weren't using, this PR removes that CSS.

Code cleanliness: Remove CSS that isn't required

---

docs/PULL_REQUEST_TEMPLATE.md

This is a template that will show up each time we make a PR in the description. It makes it easy to fill out and has a checklist of things so we don't forget anything. We can always update it however we want in the future if we are missing something or don't find other parts useful.

[Documentation] PR Template

---

docs/PULL_REQUEST_TEMPLATE.md

I noticed a few formatting things were off and some pieces were not clear. I've updated formatting and added clarification on pieces I thought were not clear.

[Docs] PR template formatting

---

frontend/src/components/commons/Tab.jsx
frontend/src/components/commons/TabNavigation.jsx
frontend/src/components/eMIB/EmibTabs.jsx
frontend/src/css/App.css
frontend/src/tests/components/commons/Tab.test.js
frontend/src/tests/components/commons/TabNavigation.test.js

Upgrading Tabs in TabNavigation to use a look and feel similar to react-bootstrap tabs (bootstrap's tabs do not support our accessibility guidelines).
Also
- Fixed translation bug
- Simplified props and state of TabNavigation
- Added css for the new structures to App.css
Before:
After:
- Pull the branch
- Make sure the formatting looks right
- Toggle language and ensure that the tab language toggles too
- **Double check that this does not bog down your machine** my work machine is running really slowly, and I want to make sure that it is some localized issue not a but with the app.

Pretty Tabs Update

---

.gitignore
REPORTING.md
SETUP.md
TESTING.md
docs/PULL_REQUEST_TEMPLATE.md
pa11y.json
reports/README.txt
run-accessibility-check.sh
run-snyk-tests.sh

Installed and configured a new Accessibility Tool that allows us to generate a report that shows all accessibility errors, warnings and notices that our application has.
**Home Page Report:**
...
**Prototype Page Report:**
...
**Status Page Report:**
...
**eMIB Sample Test Page Report (analyse only the home page of the sample test, since the pa11y tool cannot analyse inside React component):**
...
(N/A)

Introducing accessibility checking tool

---

frontend/src/components/eMIB/Evaluation.jsx
frontend/src/components/eMIB/HowTo.jsx
frontend/src/components/eMIB/Overview.jsx
frontend/src/components/eMIB/TestInstructions.jsx
frontend/src/components/eMIB/TipsOnTest.jsx

Adding Stubbed overview; Tips on Taking Emib; Test Instructions; and Evaluation components to help with future PRs: this will allow one developer to focus on formatting the paging of these components within the HowTo component while another can flesh out the stubbed component, minimizing merge conflicts.
1.  Go to HowTo page.
2.  Check that divs from stubbed components are visible

[Pre-feature] Stubbing Instructions Components

---

frontend/src/components/eMIB/Overview.jsx
frontend/src/css/App.css
frontend/src/text_resources.js

Added the content of the Overview in its respective component and format everything.
Note that the **link** in the Overview is not working for now, since it will redirect to another section of the How To page that is not built yet.
**These changes generate a new compiling warning related to the empty _href_. However, this warning will be gone as soon as we build the other component that this link refers to.**
**Whole Page:**
**Important Section Added [ENGLISH]:**
**Important Section Added [FRENCH]:**
1.  Go to Prototype tab.
2.  Click _Start eMIB Sample Test_.
3. Click _Next_.
4. Make sure that the Overview looks good and the same as the wireframes. …

[How To Page] Building the Overview Section

---

frontend/src/components/eMIB/Overview.jsx
frontend/src/components/eMIB/TipsOnTest.jsx
frontend/src/css/App.css
frontend/src/text_resources.js

Added the content of the Tips on Taking the eMIB in its respective component and format everything.
Note that the **link** in this component is not working for now, since it will redirect to another section of the How To page that is not built yet.
**These changes generate a new compiling warning related to the empty _href_. However, this warning will be gone as soon as we build the other component that this link refers to.**
**Important Section Added [ENGLISH]:**
**Important Section Added [FRENCH]:**
1. Go to Prototype tab.
2. Click _Start eMIB Sample Test_.
3. Click _Next_.
4. Make sure that the Tips on Taking the eMIB looks good and the same as the …

[How To Page] Building the Tips on Taking the eMIB Section

---

frontend/src/components/eMIB/Overview.jsx
frontend/src/components/eMIB/TipsOnTest.jsx
frontend/src/text_resources.js

This Pull Request removes the links in Overview and Tip on Taking the eMIB components and replaces them by adding content.
**Overview Component [EN]:**
**Overview Component [FR]:**
**Tips on Taking the eMIB Component [EN]:**
**Tips on Taking the eMIB Component [FR]:**
1.  Go to Prototype tab.
2.  Click _Start eMIB Sample Test_.
3.  Take a look at the Overview and Tip on Taking the eMIB components and make sure that the English and French versions are fine, mainly near 'Key Leadership Competencies'.
4.  Take a look at Evaluation component and make sure that the link 'Key Leadership Competencies' works well.
Applicable for …

[Pre-Test Information] Links of Overview and Tips on Taking the eMIB Fixes/Updates

---

frontend/src/components/commons/ContentContainer.jsx
frontend/src/components/commons/ProgressPane.jsx
frontend/src/css/App.css

I spent some time with the UX Designer in order to match exactly the pre-test information in the wireframes design. That being said, I updated some visual aspects. 
I mainly added padding and updated button colors (background color for hover, active and focus states).
**Padding updates on the progress bar and on h1, h2 and h3 tags:**
**Buttons padding updates:**
**Primary button color updates [hover state]:**
**(hover)**
**Secondary button color updates [hover state]:**
**(hover)**
**Primary button color updates [focus state]:**
**(focus)**
**Secondary button color updates [focus state]:**
**(focus)**
**Primary and Secondary buttons color updates [active state]:**
Keep the same color has the primary button default color.
**(Primary)**
**(Secondary)**
Manual …

[Pre-Test Information] Style Bug Fixes

---

frontend/src/App.js
frontend/src/components/commons/ProgressPane.jsx
frontend/src/components/commons/SideNavigation.jsx
frontend/src/components/commons/TabNavigation.jsx
frontend/src/components/eMIB/Evaluation.jsx
frontend/src/components/eMIB/Overview.jsx
frontend/src/components/eMIB/TestInstructions.jsx
frontend/src/components/eMIB/TipsOnTest.jsx
frontend/src/css/App.css
frontend/src/css/cat-theme.css

Joey and I did another overview of general styles for our PSC Aurora Theme. We double checked all the colours for accessibility. 
Individual changes are described in each commit.
Since we decided to treat App.css as a "theme override" for Auora, I've also re-named the file to reflect that convention. 
1.  Click through pre-test instruction to see style changes.
Any concerns that need to be addressed in product usability testing:
- There will be a second follow up PR to this, but we didn't want to make it too big.

Dev / Design Pairing: Caley / Joey General Styles

---

frontend/src/Status.jsx
frontend/src/text_resources.js

Images look good so far - just one that needed a better description 
1.  Hover over ThunderCAT logo to see alt text.

Accessibility review of site: images

---

frontend/public/index.html
frontend/src/css/cat-theme.css

Added _Rubik_ and _Nunito Sans_ font styles in _index.html_. Applied these two new font styles to the whole application.
**< h1 >** tags are now using _Rubik_ font style.
All other tags, except **< i >** tags, are now using _Nunito Sans_ font style.
An exception has been added to all **< i >** tags, since this was causing icon display issues:
**References:**
Rubik: https://fonts.google.com/specimen/Rubik?selection.family=Rubik
Nunito Sans: https://fonts.google.com/specimen/Nunito+Sans
**Before:**
**After:**
1.  Navigate in the application and make sure that the font styles are right and look good.
Applicable for all code …

Arial font bug fix

---

frontend/package.json
frontend/yarn.lock

This patch solves [Prototype Pollution](https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-173692), related to [CWE-471](https://cwe.mitre.org/data/definitions/471.html) caused by handlebars@4.0.12. Also fixed other dependencies to remove errors and warnings during compilation.
Changes:
- handlebars 4.0.12 -> 4.1.0 (solves High Vulnerability Prototype Pollution)
- react-scripts 2.1.3 -> 2.1.5 (2.1.3 requires earlier version of handlebars)
- added typescript (missing peer dependency for react-scripts)
- removed all devDependencies as unnecessary (versions of eslint conflicted with other deps)
Image of snyk test for frontend after patch
1.  Delete …

[Vulnerability Patch] CWE-471 caused by handlebars@4.0.12

---

frontend/src/components/commons/SideNavigation.jsx
frontend/src/components/commons/TabNavigation.jsx
frontend/src/css/cat-theme.css
frontend/src/css/side-nav.css

Fixes side navigation on IE by:
- Removing all flex styles, since they are not totally compatible with IE
- Replacing _Flex_ by _Grid-Cell_ styles
- Making the Tab Navigation static (width of 1140, same as the default width)
**Chrome:**
**IE:**

Bug fix - IE side navigation

---

docs/PULL_REQUEST_TEMPLATE.md

Update to PR Template:
- Removed Concerns section
- Removed 'My code follows the style guidelines of this project' from checklist
N/A
N/A
N/A

[Documentation] PR template update

---

frontend/src/components/commons/SideNavigation.jsx
frontend/src/tests/components/commons/SideNavigation.test.js

This PR fixes the look and feel of SideNavigation so that the buttons jump to the correct component and 
that the selected button dynamically updates depending on how far you have scrolled.
1.  Go the eMIB Test
2.  Select the in-test instructions page
3.  Scroll through the page, verify that the buttons on the side update
4.  Click buttons on the side, verify that the correct component is displayed
5.  Repeat for IE.
Applicable for all code …

[Functionality] Side Navigation Dynamic Scrolling

---

frontend/src/Status.jsx

We'll need our URLs to be relative so they work on a server and not just localhost.
1.  Go to Status page and all checks should be successful.

[Bug fix] Make URLS relative so they work on the server

---

frontend/src/components/commons/SideNavigation.jsx
frontend/src/components/commons/Tab.jsx
frontend/src/components/commons/TabNavigation.jsx
frontend/src/components/eMIB/EmibTabs.jsx
frontend/src/tests/components/commons/SideNavigation.test.js
frontend/src/tests/components/commons/Tab.test.js
frontend/src/tests/components/commons/TabNavigation.test.js
frontend/src/text_resources.js

Fixed tags, elements, and other meta data for Side and Tab Navigation, and Tab components to meet accessibility requirements.
N/A
1.  Navigate into the test in IE (Narrator only works in IE)
2.  Turn on the Narrator
3.  Ensure that the narrator properly detects the menus, selected an unselected tabs
4,. Ensure that there are not cosmetic differences in IE or Chrome

[Accessibility] Navigation Overhaul

---

frontend/src/text_resources.js

Replacing stubbed translations with actual translations; repalcing some titles/headers that were in all caps
1.  Go to Prototype -> Start eMIB -> Skip through pre-test instructions
2.  Look at the in-test background tab
3. Verify that french translation is present

[Background] Adding french translations

---

frontend/src/components/commons/SideNavigation.jsx
frontend/src/css/side-nav.css

Addition of divider between sub-components of a side navigation.
1.  Go to Prototype-> Start eMIB -> traverse pre-test instructions
2.  Verify that the side navigation components (in-test instructions and background tab) have dividers

[Side Navigation] Divider

---

frontend/src/components/commons/PopupBox.jsx
frontend/src/css/cat-theme.css
frontend/src/tests/components/commons/PopupBox.test.js

Created a new popup box generic component that allows us to add and customize a popup window anywhere in the application.
However, this component isn't used anywhere for now, but we'll need it soon, especially for the image popups and for the _Submit Test_ and _Quit Test_ actions that will be created in the next PRs.
You can use it wherever you want and here is how:
**Popup Box with 1 Button (without action):**
**Result:**
**Popup Box with 2 Buttons (without action):**
**Result:**
**Adding Action to a button:**
You also need to import the component itself and the BUTTON_TYPE variable:
***Obviously, instead of using hard coded text, you must use the text_resources file.**
N/A …

[Generic Component] Created New Popup Box Component

---

frontend/src/components/commons/PopupBox.jsx
frontend/src/components/commons/SystemMessage.jsx
frontend/src/components/eMIB/Emib.jsx
frontend/src/css/emib.css
frontend/src/tests/components/commons/PopupBox.test.js
frontend/src/text_resources.js

I completed the submit test flow by adding the generic popup box component when selecting the **Submit test** button. This popup box also contains a warning message, so I also used the generic system message component to get that.
**English Version:**
French Version:**
***Note that the translation hasn't been done in this PR, except for the popup box title and for the buttons. This translation will be done in another PR.**
1.  Start the eMIB sample test.
3.  Click **Submit test** and make sure that all buttons in the popup box work well.

[Submit Test Flow] Completed the Submit Test Flow

---

frontend/src/components/eMIB/Emib.jsx
frontend/src/components/eMIB/OrganizationalStructure.jsx
frontend/src/components/eMIB/TeamInformation.jsx
frontend/src/components/eMIB/TestExamples.jsx
frontend/src/components/eMIB/TestInstructions.jsx
frontend/src/css/cat-theme.css
frontend/src/text_resources.js

Changed order of Instructions and Split Testinstructions into TestInstructions and TestExamples
1.  Go to Prototype -> Start eMIB
2.  Navigate through pre-test instructions, verifying that they look correct
3.  Start Test
4. Verify that in-test instructions look correct

Split instructions

---

frontend/src/components/commons/ProgressNode.jsx
frontend/src/components/commons/ProgressPane.jsx
frontend/src/tests/components/commons/ProgressNode.test.js
frontend/src/tests/components/commons/ProgressPane.test.js

Addition of clickable functionality to the progress bar and update for tests.
No real screenshots/visual differences.
1.  Go to Prototype Page
2.  Start eMIB
3. Verify that you can navigate through the pre-test instructions by clicking on the nodes in the progress bar.

[Pre-Test Information] Clickable Progress Bar

---

docs/common-debugging.md

Documenting how to solve the network connection error:
`frontend_1 | info There appears to be trouble with your network connection. Retrying...
frontend_1 | info There appears to be trouble with your network connection. Retrying...
frontend_1 | error An unexpected error occurred: "https://registry.yarnpkg.com/ p-is-promise/-/p-is-promise-2.0.0.tgz: Client network socket disconnected before secure TLS connection was established".
frontend_1 | info If you think this is a bug, please open a bug report with the information provided in "/home/node/yarn-error.log".
frontend_1 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
frontend_1 | yarn run v1.12.3
frontend_1 | \$ react-scripts start
frontend_1 | /bin/sh: 1: react-scripts: not found
frontend_1 | …

[Doc] Debugging Network Connection error

---

frontend/src/helpers/regexValidator.js
frontend/src/tests/components/authentication/regexValidator.test.js

I implemented new validation rules using RegEx for the first and last names, for the email and for the password.
(N/A)
- There is nothing you can do right now to test these new validation rules, but you can make sure that the tests are covering most of the common errors people can do.

[Login & Create Account] Introducing Fields Validation

---

frontend/src/components/eMIB/Inbox.jsx
frontend/src/text_resources.js

Adding text for emails from sample test
1.  Go to Prototype -> Start test
2.  Click through pre-test instructions
3.  Start test, enter inbox.

Email sample contents

---

frontend/src/components/eMIB/Email.jsx
frontend/src/components/eMIB/Inbox.jsx
frontend/src/tests/components/eMIB/Email.test.js
frontend/src/tests/components/eMIB/Inbox.test.js
frontend/src/text_resources.js

Fleshing out email view, with relevant changes to tests and Inbox.
Also added functionality that if either button is clicked, the email is marked as having a response. This is for testing and demoing and will be fleshed out properly in another PR
NOTES (There are known issues that will be fixed in later PRs)
1) Graphical glitch 1: There is a slight graphical glitch on Chrome only for the stubbed emails (emails shorter than a certain length). See screenshots.
2) Graphical glitch 2: There is another glitch in IE, also in screenshots
3) Clicking the buttons causes the text "You responded with 0 replies and 0 tasks". These numbers are currently hard coded and will not change
4) Leaving the Inbox tab resets the states of all emails. This will be fixed when Redux is added
5) The emails …

[Inbox] Email view

---

frontend/src/components/eMIB/Email.jsx
frontend/src/components/eMIB/Inbox.jsx
frontend/src/css/inbox.css

I fixed two graphical bugs that were documented in PR https://github.com/code-for-canada/project-thundercat/pull/158.
**IE Bugs:**
---
**Before Changes:**
**Bug Fixed:**
**Chrome Bugs:**
---
**Before Changes:**
**Bug Fixed:**
**Minor Bugs that still there (IE Only):**
---
When there are empty emails in IE, the auto width isn't working well. It takes the width depending on the content of the email like that:
However, we should never have empty emails. As soon as we are adding some content, it looks as it should:
4.  Make sure the emails …

[Inbox] Chrome and IE Bug Fixes

---

frontend/src/components/commons/BackToTop.jsx
frontend/src/components/eMIB/Email.jsx
frontend/src/components/eMIB/EmailPreview.jsx
frontend/src/components/eMIB/Inbox.jsx
frontend/src/css/inbox.css
frontend/src/tests/components/eMIB/EmailPreview.test.js

Design pairing with Joey.
Most of this includes subtle changes to the formatting/style of email preview, however there are a couple noteworthy changes:
- 5a9ece6 Removed the trimming function added in #159 (not needed with larger preview size)
- 4a65185 Changing parameters for revealing 'Back To Top' button
-> Joey found user documentation that stated that a 'Back To Top' Button should only appear in larger, multi-screen situations and can be confusing otherwise
-> Only appears if the document height is > 1800 (only on the Test Examples page)
-> Will not appear at all until you scroll at least 1000 px
Before:
After:
Before:
After:
Before:
After:
Before:
After:
1.  Go to Prototype …

[Design Review] Design fixes

---

frontend/src/App.js

[Merging fix into PR] Use class fixed top instead of zindex

---

frontend/src/components/eMIB/ActionViewEmail.jsx
frontend/src/components/eMIB/Email.jsx
frontend/src/tests/components/eMIB/ActionViewEmail.test.js
frontend/src/tests/components/eMIB/Email.test.js

- Refactored Email.jsx to cut down on confusion of variable names (email containing actions, so of which are emails; ~~email~~ -> action, some of which happen to be emails)
- Changed parameters passed to ActionViewEmail, to take an action rather than a 5 individual parameters; also take emailId as a parameter; these will be needed when editing emails/tasks
-Updated tests to meet these changes
Should be no visual changes.
1.  Start the eMIB, go through the pretest instructions; go to the inbox
2. Verify that that adding a test works as expected.
~~- [ ] I have made corresponding changes to the …

[Refactor] Refactoring Email and children components/tests

---

frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/components/eMIB/EditTask.jsx
frontend/src/components/eMIB/Email.jsx
frontend/src/text_resources.js

I created the **'Add Task Form'** based on the design (read only). 
Note that the tool tip functionality hasn't been implemented yet in this form.
**Form View:**
1.  Start the eMIB Sample test.
3.  Click on _Inbox_ tab.
4.  Click on _Add task_ and make sure that the form looks good and also make sure that the email ID and email subject are the right ones in the form.

[Add Task] Created the Add/Edit task form

---

frontend/src/components/eMIB/constants.js
frontend/src/tests/components/eMIB/EditActionDialog.test.js

Fix unit tests after prop types changed.
Test only change.

[Master fix] Fix unit tests after prop types changed

---

frontend/src/components/eMIB/Email.jsx
frontend/src/tests/components/eMIB/Email.test.js

Fix from Caley as a possible patch for the re-render bug

Try to get state to update properly

---

frontend/src/components/eMIB/ActionViewEmail.jsx
frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/components/eMIB/Email.jsx
frontend/src/modules/EmibInboxRedux.js
frontend/src/tests/components/eMIB/ActionViewEmail.test.js
frontend/src/tests/components/eMIB/EditActionDialog.test.js
frontend/src/tests/modules/EmibInboxRedux.test.js

This fixed the breaking bug in #188, where an edited email creates a new email rather than editing the old one.
Note: this takes in all email data from the redux state, rather than just the associated parent email. However, taking only some of the date seems to break the link that allows re-rendering
- Bug fix (non-breaking change which fixes an issue) - for the breaking change in PR #188
Add a new email response:
Fill out the form and save the response:
New email is added; edit the response:
Update the fields as desired and save the response:
Response is updated:
1.  Go to Prototype -> Start eMIB -> …

[Edit Email] Edit email with save

---

frontend/src/components/eMIB/CollapsingItemContainer.jsx
frontend/src/components/eMIB/EditTask.jsx

Simple style update in _'CollapsingItemComponent.jsx'_ and _'EditTask.jsx'_ components to match the design.
**CollapsingItemContainer:**
**Edit Task:**
4.  Click on _Create a task_ and make sure that the form is looking good.
5.  Save this new task and make sure that the _arrow icon_ in the Collapsing Item Container looks good.

[Design Session] Updated style in 'CollapsingItemContainer' and 'EditTask' components

---

frontend/src/components/eMIB/ActionViewEmail.jsx
frontend/src/modules/EmibInboxRedux.js
frontend/src/tests/components/eMIB/ActionViewEmail.test.js
frontend/src/tests/modules/EmibInboxRedux.test.js

Added functionality allowing deletion of email responses.
**After adding 3 emails:**
**1st email:**
**2nd email:**
**3rd email:**
**Delete email 2:**
**After deleting 2nd email:**
**Delete email 1:**
**After deleting 1st email:**
**Delete new 1st email (originally 3rd email):**
**After deleting all emails:**
1.  Prototype -> Start eMIB -> Instructions Page 5 -> Start Test -> Inbox Tab
2.  Add Email Responses
3.  Delete Email Responses

[Delete Email] Delete email functionality

---

frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/components/eMIB/EditEmail.jsx

Design Changes from pair programming with @joeyhua 
Before:
After:
1.  Go to the Inbox tab within the eMIB
2.  Click "Add Email Response"
3.  See the changes

[Email Response Dialog] Pairing design changes

---

frontend/src/components/eMIB/EditEmail.jsx
frontend/src/components/eMIB/EditTask.jsx

I simply updated the max character count values, since the current values were pretty low.
**Email Response Form:**
**Task Form**
4.  Open email response and task forms and make sure the the max character count is working well.

[Email Response & Task Forms] Updated max character count values

---

frontend/src/components/commons/PopupBox.jsx
frontend/src/components/eMIB/EditEmail.jsx
frontend/src/components/eMIB/EditTask.jsx
frontend/src/css/cat-theme.css

I met @joeyhua and updated the style of the following components to match the design:
- PopupBox.jsx
- EditEmail.jsx
- EditTask.jsx
**Popup Box**
---
**Before:**
**After:**
**Edit Email**
---
**Before:**
**After:**
**Edit Task**
---
**Before:**
**After:**
- Make sure that the popup boxes, the email response form and the task form are still looking good and work as expected.

[Design Session] Updated PopupBox, Email Response Form and Task Form styles

---

docs/PULL_REQUEST_TEMPLATE.md

Updates to the PR template based on new browser requirements, and use of other checklist items.

Update PR template

---

frontend/src/components/eMIB/EditEmail.jsx
frontend/src/css/cat-theme.css

Changes added during design pairing with Joey
Before:
After:
1.  Go to the Inbox tab in the tab
2.  Open an Email response
~~- [ ] My changes generate no new compiler warnings~~

[Email Response Multiselect 3] Email response dropdown design pairing

---

docs/common-debugging.md

Adding documentation for the nginx bug that @caleybrock  and I keep encountering
N/A
N/A
N/A

[Documentation] Bug fix documentation

---

frontend/src/components/commons/ConfirmStartTest.jsx
frontend/src/components/eMIB/Emib.jsx
frontend/src/text_resources.js

Reverts code-for-canada/project-thundercat#237

Revert "[Accessibility] Remove unnecessary warnings from dialogs"

---

frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/components/eMIB/EditEmail.jsx
frontend/src/components/eMIB/EditTask.jsx

I met with @joeyhua  and updated the style in 'EditActionDialog', 'EditEmail' and 'EditTask' components to match the design.
**Email Response Action Dialog**
---
**Before:**
**After:**
**Task Action Dialog**
---
**Before:**
**After:**
4.  Create an email response and a task and make sure that these dialogs look good, especially the padding/margin between the text areas and the scroll bar.

[Design Session] Updated style in 'EditActionDialog', 'EditEmail' and 'EditTask'

---

frontend/src/components/commons/ConfirmStartTest.jsx
frontend/src/components/eMIB/Emib.jsx
frontend/src/text_resources.js

Reverts code-for-canada/project-thundercat#240
Fixes console warnings in the original PR.

Revert "Revert "[Accessibility] Remove unnecessary warnings from dialogs""

---

frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/helpers/editActionDialogHelper.js
frontend/src/tests/components/eMIB/EditActionDialog.test.js

Reverts code-for-canada/project-thundercat#245
Fixed the closing email dialog bug.

Revert "Revert "[Cancel Confirmation Message] Displaying message only if there are changes""

---

frontend/src/components/commons/TestFooter.jsx
frontend/src/components/eMIB/constants.js

Replace test footer with react bootstrap navbar to see if it works better for accessibility. Looks almost exactly the same.
1.  Go to the sample test and use the footer.

Replace test footer with react bootstrap navbar

---

frontend/src/modules/sampleEmibJson.js

FR Translation - Missing "et"

---

frontend/src/components/commons/PopupBox.jsx

Aria labels on dialogs were causing problems - this fixes that.
No visual change.
No visible changes. All dialogs should work as expected. 

Correct aria labels on dialogs

---

Dockerfile.dev
app.json
frontend/Dockerfile.heroku
heroku.yml

Setup heroku review apps frontend. We'll use this until we setup the dev server version.
Based on: https://github.com/maxneuvians/project-thundercat/pull/1

Setup frontend heroku frontend

---

frontend/src/components/commons/Notepad.jsx
frontend/src/components/eMIB/EmibTabs.jsx

Fix compiler warnings on master.
docker-compose up and see no frontend warnings

Fix compiler warnings on master

---

docker-compose-dev.yml

Create a docker-compose-dev file to use on current dev server deployments. The main purpose is to ensure the port on the dev server is 443.

Update a dev compose file

---

frontend/src/App.js
frontend/src/components/commons/QuitTest.jsx
frontend/src/text_resources.js

Add canada logo and quit icon.

Add Canada logo and update quit icon

---

frontend/src/components/eMIB/OrganizationalStructure.jsx
frontend/src/components/eMIB/TeamInformation.jsx
frontend/src/text_resources.js

It was suggested that since we are using a tree view, that we add instructions for those who are not familiar with the format.
1.  Go to the sample test background information.
2. Click on the image description button to get the popup.

Add org chart instructions

---

frontend/package.json
frontend/public/index.html
frontend/src/components/commons/BackToTop.jsx
frontend/src/components/commons/Notepad.jsx
frontend/src/components/commons/QuitTest.jsx
frontend/src/components/commons/Settings.jsx
frontend/src/components/commons/SystemMessage.jsx
frontend/src/components/commons/TreeNode.jsx
frontend/src/components/eMIB/ActionViewEmail.jsx
frontend/src/components/eMIB/CollapsingItemContainer.jsx
frontend/src/components/eMIB/EditActionDialog.jsx
frontend/src/components/eMIB/EditEmail.jsx
frontend/src/components/eMIB/Email.jsx
frontend/src/components/eMIB/EmailPreview.jsx
frontend/src/components/status/StatusCheck.jsx
frontend/src/components/status/SystemCheck.jsx
frontend/src/tests/components/commons/SystemMessage.test.js
frontend/src/tests/components/eMIB/ActionViewEmail.test.js
frontend/src/tests/components/eMIB/CollapsingItemContainer.test.js
frontend/src/tests/components/eMIB/EditActionDialog.test.js
frontend/src/tests/components/eMIB/Email.test.js
frontend/src/tests/components/eMIB/EmailPreview.test.js
frontend/yarn.lock

Replace using fontawesome with CSS with the font awesome package for react to guarantee it shows up for IE.
Use the review app - some of these are not perfect, but we need to test to see if this theory works.
Icons are throughout application - there should be none missing.

[Bug fix] Font awesome doesn't show up in IE

---

deploy.sh

Little script to automate the docker deployment on the server until we build the pipeline.

Deployment script

---

frontend/src/components/authentication/RegistrationForm.jsx
frontend/src/css/registration-form.css
frontend/src/text_resources.js

This PR is introducing a whole new validation structure in the registration form. Now, the validation will be done on submit instead of live. Also, new errors have been added for first name, last name and email address.
The screen reader users are also able to navigate in this registration form and get all errors encountered.
**Registration form on first load:**
**Registration form with all invalid fields (after clicking on _Create account_ button):**
**Registration form with one invalid field (after clicking on _Create account_ button again):**
**Registration form with all valid fields, but account already exists:**
1.  Open the registration form from …

[Accessibility] Registration form errors refactoring

---

frontend/src/components/authentication/RegistrationForm.jsx
frontend/src/modules/LoginRedux.js
frontend/src/text_resources.js

This PR is introducing a fix related to the "password too common" error. Before these changes, we were getting the following error when creating an account using the password "Password1!" for example:
I also refactored the _handleSubmit_ function, since it was kind of messy and confusing with these new changes.
**Initial form view:**
**Trying to create an new account with an existing email address:**
**Trying to create a new account using a too common password (for example "Password1!"):**
2.  Try to create an new account with an already existing account and make sure …

[Bug Fix] Fixing common password bug

---

backend/config/urls.py
backend/views/test_questions_view.py

Adding view and url registration of test-questions API
Accessing `http://localhost/api/test-questions/?test_name=emibSampleTest` when logged in
Accessing `http://localhost/api/test-questions/?test_name=emibPizzaTest` when logged in as admin
Accessing `http://localhost/api/test-questions/?test_name=emibPizzaTest` when not logged in

[Test API] Test questions api

---

backend/config/urls.py
backend/tests/test_retrieve_test_view.py
backend/views/retrieve_test_view.py
backend/views/test_instructions_view.py
backend/views/test_meta_data_view.py
backend/views/test_questions_view.py

Adding core functions and tests for retrieving data from DB.
N/A (see later PRs)
N/A

[Test API] Adding core functions and tests for retrieving all test data

---

backend/tests/postman/ThunderCAT.postman_collection.json
backend/tests/test_retrieve_test_view.py
backend/views/retrieve_test_view.py

Code to find questions (and other relevant children) for the given test and return in a usable format
NOTE: All the below are when logged in as an admin
Accessing `http://localhost/api/test-questions/?test_name=emibPizzaTest`:
Accessing `http://localhost/api/test-questions/?test_name=emibSampleTest`

[Test Structure] Load questions from DB

---

frontend/src/text_resources.js

French translations for the settings dialog.
1.  Open up the settings dialog in the top right of the navigation in french.
~~- [ ] My changes generate no new compiler warnings~~

French translations for settings dialog

---

frontend/src/modules/LoadTestContentRedux.js
frontend/src/testDefinition.js
frontend/src/tests/modules/LoadTestContentRedux.test.js

This PR is introducing the action type/actions/reducer/initial state to get the test instructions and update the redux state.
**How to use these new actions:**
**Then if we print the redux state called 'testInstructions':**
**We get that result:**
- you can test these new actions using the code shown above in any desired file of the project. You'll just need to assure the redux connection with this selected file.

[Test Instructions] Getting test instructions from the back end

---

frontend/src/modules/LoadTestContentRedux.js
frontend/src/tests/modules/LoadTestContentRedux.test.js

This PR is introducing the action type/actions/reducer/initial state to get the test questions and update the redux state.
**How to use these new actions:**
**Then if we print the redux state called 'testQuestions':**
**We get that result:**
- you can test these new actions using the code shown above in any desired file of the project. You'll just need to assure the redux connection with this selected file.

[Test Questions] Getting test questions from the back end

---

frontend/src/Home.jsx
frontend/src/components/authentication/LoginForm.jsx
frontend/src/components/authentication/RegistrationForm.jsx
frontend/src/modules/LoginRedux.js
frontend/src/tests/modules/LoginRedux.test.js
frontend/src/text_resources.js

This PR is introducing new logic to change/update the page title when the registration form or login form contains error(s). For example, on first page load or when there is no error, the page's title is "CAT Home". However, if you fill out, for example, the registration form, click _Create account_ button and get error(s), the page's title will become "Error - CAT Home". This idea was suggested by David.
**Initial View:**
**When the registration form contains error(s):**
**When the errors are all fixed:**
**Exactly the same logic with the login form.**
2.  Make sure the the page's title is "CAT Home".
3.  Fill out the form, but with intentional …

[Accessibility] Changing page title on registration form error

---

frontend/src/components/commons/Notepad.jsx
frontend/src/components/eMIB/EmailPreview.jsx
frontend/src/text_resources.js

Content QA with Joey and Siobhan. 

Content updates

---

frontend/src/text_resources.js

French Content Updates

---

frontend/src/text_resources.js

Update 2 FR content

---

frontend/src/text_resources.js

Updated to match agreed upon style guidelines

Title / Field standardization

---

frontend/src/components/commons/TestFooter.jsx
frontend/src/components/commons/Timer.jsx
frontend/src/tests/components/commons/Timer.test.js
frontend/src/text_resources.js

Builds a timer component (all times default to 0) and adds it to the test footer.
1.  Go to the sample test.
2.  Instructions should have no timer.
3.  Once test is started a 00:00:00 timer should appear.

Timer component

---

frontend/src/components/eMIB/EmibIntroductionPage.jsx
frontend/src/text_resources.js

Updated content to match prototype (EN)

[Content update] Update to Test Instructions Overview

---

frontend/src/text_resources.js

Content update for settings dialog

[Content update] Update settings dialog title

---

frontend/src/Home.jsx
frontend/src/tests/Home.test.js
frontend/src/text_resources.js

Update welcome message on the home page.

[Content updates] Home page

---

frontend/src/text_resources.js

Update text of side nav titles.

[Content updates] Side nav titles

---

frontend/src/components/commons/Notepad.jsx
frontend/src/text_resources.js

Update text of notepad toggle button.
Bug fix (non-breaking change which fixes an issue)

[Content updates] Notepad toggle button

---

frontend/public/manifest.json
frontend/src/text_resources.js

[Content update] Fix spelling of app title

---

frontend/src/SelectLanguage.jsx
frontend/src/components/commons/Translation.jsx

Store the strings outside of the render function so they can be clearly seen. Suggestion from Francis.
1.  Go to the language selection landing page.
2.  Switch languages.

[Code clear] Store strings outside of render

---

frontend/src/components/commons/ConfirmStartTest.jsx
frontend/src/text_resources.js

Update timer dialog to display how much time the timer will have.
The sample test has unlimited time.
Next we'll want to load this time information from the metadata api.
1.  Go to the sample test.
2. click start test.

[Content update] Update timer dialog

---

SETUP.md

This PR is introducing an updated version of the _SETUP.md_ file. _Linting_ section has been updated and a new section called _Other Useful Configurations_ has been added.
(N/A)
(N/A)

[Documentation] Updating setup md file

---

backend/tests/test_retrieve_test_view.py
backend/views/retrieve_test_view.py

Updating API and tests to retrieve the overview from the database
sequel to #415 
http://localhost/api/test-meta-data/?test_name=emibSampleTest
See screenshot

[Test Structure] Overview Part 2: API update

---

frontend/src/components/eMIB/TeamInformation.jsx
frontend/src/text_resources.js

Reverts code-for-canada/project-thundercat#423

Revert "[Team Information] Populating team information tree view with api"

---

backend/custom_models/migrations/0013_upload_background_tree_view_info.py
backend/tests/test_retrieve_test_view.py
backend/views/retrieve_test_view.py
frontend/src/components/eMIB/OrganizationalStructure.jsx
frontend/src/text_resources.js

Reverts code-for-canada/project-thundercat#422

Revert "[Organizational Structure] Populating organizational structure tree view with api"

---

frontend/src/App.js

Fixes the 400 error in the console.
Added logic to skip the verification if the auth_token is undefined (i.e. if there is nothing to verify)
No 400 error in console:
Open the application, open the console, see that there is no 400 error

[Bug Fix] Remove 400 from console

---

frontend/src/components/eMIB/OrganizationalStructure.jsx
frontend/src/components/eMIB/TeamInformation.jsx
frontend/src/helpers/transformations.js
frontend/src/tests/components/eMIB/transformations.test.js

This removes all hard coding for the tree view, generates it from the API response. This makes the component more generic and should allow for the pizza test to be used without problem.
No changes to interface.
1.  Go to the background info and click on the image descriptions. They should match the actual images.

Generalize creating the tree view based on the API

---

frontend/src/components/commons/PopupBox.jsx
frontend/src/components/commons/QuitTest.jsx
frontend/src/components/eMIB/EditActionDialog.jsx

Dropping unused hr from styles
No visual difference
No differences in behaviour

[Code Cleanup] Dropping unused hr styles

---

frontend/src/modules/LoadTestContentRedux.js
frontend/src/testDefinition.js

This PR is introducing a fix for the permission issues we've got when trying to view the Pizza test when logged in.
**Sample Test**
---
**We can access the sample test logged in or not:**
_Logged out_
_Logged in_
_Test Content_
**Pizza Test**
---
**We can access the pizza test only if we are logged in:**
_Logged out_
_Logged in_
_Test Content_
**In order to be able to view this content, I had to comment/modify part of the code in _TeamInformation.jsx_ component, since it is not generic yet:**
1.  Try to access the Sample Test (logged in and not logged in) and make sure that you are able to see the meta data and the test content.
2. …

[Authentication] Authentication fix on protected test content APIs

---

backend/custom_models/language.py
backend/views/retrieve_test_view.py

Fixes the datetime error in the console; replace datetime with timezone
To replicate, see testing.
Before fix:
After Fix:
Go to the eMIB sample overview page (or really any page).
Refresh page

[Bug Fix] Fix date time error

---

frontend/src/components/authentication/RegistrationForm.jsx
frontend/src/text_resources.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Go to login page

[Accessibility] Replace required asterisks with optional label

---

README.md

Documentation update.
FYI - @siobhanozege I'm adding this here so that it's super easy to find.

[Docs] Update technical requirements in README

---

frontend/src/Status.jsx
frontend/src/text_resources.js

Suggested by @fnormand01 : https://github.com/code-for-canada/project-thundercat/pull/479#discussion_r303930467

Status page documentation update.

---

docs/test-definition.md

Adding a document explaining how we define tests currently in the application.

[Docs] Test definition 
